// This file was generated for SObject PermissionSetLicense, API Version v43.0 at 2018-07-30 03:48:10.293154661 -0400 EDT m=+56.637886300

package sobjects

import (
	"fmt"
	"strings"
)

type PermissionSetLicense struct {
	BaseSObject
	CreatedById                                      string `force:",omitempty"`
	CreatedDate                                      string `force:",omitempty"`
	DeveloperName                                    string `force:",omitempty"`
	ExpirationDate                                   string `force:",omitempty"`
	Id                                               string `force:",omitempty"`
	IsDeleted                                        bool   `force:",omitempty"`
	Language                                         string `force:",omitempty"`
	LastModifiedById                                 string `force:",omitempty"`
	LastModifiedDate                                 string `force:",omitempty"`
	MasterLabel                                      string `force:",omitempty"`
	MaximumPermissionsAccessCMC                      bool   `force:",omitempty"`
	MaximumPermissionsActivateContract               bool   `force:",omitempty"`
	MaximumPermissionsActivateOrder                  bool   `force:",omitempty"`
	MaximumPermissionsAddAnalyticsRemoteConnections  bool   `force:",omitempty"`
	MaximumPermissionsAddDirectMessageMembers        bool   `force:",omitempty"`
	MaximumPermissionsAllowEmailIC                   bool   `force:",omitempty"`
	MaximumPermissionsAllowLightningLogin            bool   `force:",omitempty"`
	MaximumPermissionsAllowUniversalSearch           bool   `force:",omitempty"`
	MaximumPermissionsAllowViewEditConvertedLeads    bool   `force:",omitempty"`
	MaximumPermissionsAllowViewKnowledge             bool   `force:",omitempty"`
	MaximumPermissionsApexRestServices               bool   `force:",omitempty"`
	MaximumPermissionsApiEnabled                     bool   `force:",omitempty"`
	MaximumPermissionsAssignPermissionSets           bool   `force:",omitempty"`
	MaximumPermissionsAssignTopics                   bool   `force:",omitempty"`
	MaximumPermissionsAuthorApex                     bool   `force:",omitempty"`
	MaximumPermissionsAutomaticActivityCapture       bool   `force:",omitempty"`
	MaximumPermissionsBulkApiHardDelete              bool   `force:",omitempty"`
	MaximumPermissionsBulkMacrosAllowed              bool   `force:",omitempty"`
	MaximumPermissionsCampaignInfluence2             bool   `force:",omitempty"`
	MaximumPermissionsCanApproveFeedPost             bool   `force:",omitempty"`
	MaximumPermissionsCanEditDataPrepRecipe          bool   `force:",omitempty"`
	MaximumPermissionsCanInsertFeedSystemFields      bool   `force:",omitempty"`
	MaximumPermissionsCanUseNewDashboardBuilder      bool   `force:",omitempty"`
	MaximumPermissionsCanVerifyComment               bool   `force:",omitempty"`
	MaximumPermissionsChangeDashboardColors          bool   `force:",omitempty"`
	MaximumPermissionsChatterComposeUiCodesnippet    bool   `force:",omitempty"`
	MaximumPermissionsChatterEditOwnPost             bool   `force:",omitempty"`
	MaximumPermissionsChatterEditOwnRecordPost       bool   `force:",omitempty"`
	MaximumPermissionsChatterFileLink                bool   `force:",omitempty"`
	MaximumPermissionsChatterInternalUser            bool   `force:",omitempty"`
	MaximumPermissionsChatterInviteExternalUsers     bool   `force:",omitempty"`
	MaximumPermissionsChatterOwnGroups               bool   `force:",omitempty"`
	MaximumPermissionsCloseConversations             bool   `force:",omitempty"`
	MaximumPermissionsConfigCustomRecs               bool   `force:",omitempty"`
	MaximumPermissionsConnectOrgToEnvironmentHub     bool   `force:",omitempty"`
	MaximumPermissionsContentAdministrator           bool   `force:",omitempty"`
	MaximumPermissionsContentWorkspaces              bool   `force:",omitempty"`
	MaximumPermissionsConvertLeads                   bool   `force:",omitempty"`
	MaximumPermissionsCreateCustomizeDashboards      bool   `force:",omitempty"`
	MaximumPermissionsCreateCustomizeFilters         bool   `force:",omitempty"`
	MaximumPermissionsCreateCustomizeReports         bool   `force:",omitempty"`
	MaximumPermissionsCreateDashboardFolders         bool   `force:",omitempty"`
	MaximumPermissionsCreatePackaging                bool   `force:",omitempty"`
	MaximumPermissionsCreateReportFolders            bool   `force:",omitempty"`
	MaximumPermissionsCreateReportInLightning        bool   `force:",omitempty"`
	MaximumPermissionsCreateTopics                   bool   `force:",omitempty"`
	MaximumPermissionsCreateWorkspaces               bool   `force:",omitempty"`
	MaximumPermissionsCustomMobileAppsAccess         bool   `force:",omitempty"`
	MaximumPermissionsCustomSidebarOnAllPages        bool   `force:",omitempty"`
	MaximumPermissionsCustomizeApplication           bool   `force:",omitempty"`
	MaximumPermissionsDataExport                     bool   `force:",omitempty"`
	MaximumPermissionsDelegatedTwoFactor             bool   `force:",omitempty"`
	MaximumPermissionsDeleteActivatedContract        bool   `force:",omitempty"`
	MaximumPermissionsDeleteTopics                   bool   `force:",omitempty"`
	MaximumPermissionsDistributeFromPersWksp         bool   `force:",omitempty"`
	MaximumPermissionsEditActivatedOrders            bool   `force:",omitempty"`
	MaximumPermissionsEditBrandTemplates             bool   `force:",omitempty"`
	MaximumPermissionsEditCaseComments               bool   `force:",omitempty"`
	MaximumPermissionsEditEvent                      bool   `force:",omitempty"`
	MaximumPermissionsEditHtmlTemplates              bool   `force:",omitempty"`
	MaximumPermissionsEditKnowledge                  bool   `force:",omitempty"`
	MaximumPermissionsEditMyDashboards               bool   `force:",omitempty"`
	MaximumPermissionsEditMyReports                  bool   `force:",omitempty"`
	MaximumPermissionsEditOppLineItemUnitPrice       bool   `force:",omitempty"`
	MaximumPermissionsEditPublicDocuments            bool   `force:",omitempty"`
	MaximumPermissionsEditPublicFilters              bool   `force:",omitempty"`
	MaximumPermissionsEditPublicTemplates            bool   `force:",omitempty"`
	MaximumPermissionsEditReadonlyFields             bool   `force:",omitempty"`
	MaximumPermissionsEditTask                       bool   `force:",omitempty"`
	MaximumPermissionsEditTopics                     bool   `force:",omitempty"`
	MaximumPermissionsEmailAdministration            bool   `force:",omitempty"`
	MaximumPermissionsEmailMass                      bool   `force:",omitempty"`
	MaximumPermissionsEmailSingle                    bool   `force:",omitempty"`
	MaximumPermissionsEmailTemplateManagement        bool   `force:",omitempty"`
	MaximumPermissionsEnableCommunityAppLauncher     bool   `force:",omitempty"`
	MaximumPermissionsEnableNotifications            bool   `force:",omitempty"`
	MaximumPermissionsExportReport                   bool   `force:",omitempty"`
	MaximumPermissionsFeedPinning                    bool   `force:",omitempty"`
	MaximumPermissionsFlowUFLRequired                bool   `force:",omitempty"`
	MaximumPermissionsForceTwoFactor                 bool   `force:",omitempty"`
	MaximumPermissionsGovernNetworks                 bool   `force:",omitempty"`
	MaximumPermissionsHideReadByList                 bool   `force:",omitempty"`
	MaximumPermissionsIdentityConnect                bool   `force:",omitempty"`
	MaximumPermissionsIdentityEnabled                bool   `force:",omitempty"`
	MaximumPermissionsImportCustomObjects            bool   `force:",omitempty"`
	MaximumPermissionsImportLeads                    bool   `force:",omitempty"`
	MaximumPermissionsImportPersonal                 bool   `force:",omitempty"`
	MaximumPermissionsInsightsAppAdmin               bool   `force:",omitempty"`
	MaximumPermissionsInsightsAppDashboardEditor     bool   `force:",omitempty"`
	MaximumPermissionsInsightsAppEltEditor           bool   `force:",omitempty"`
	MaximumPermissionsInsightsAppUploadUser          bool   `force:",omitempty"`
	MaximumPermissionsInsightsAppUser                bool   `force:",omitempty"`
	MaximumPermissionsInsightsCreateApplication      bool   `force:",omitempty"`
	MaximumPermissionsInstallPackaging               bool   `force:",omitempty"`
	MaximumPermissionsIotUser                        bool   `force:",omitempty"`
	MaximumPermissionsLightningConsoleAllowedForUser bool   `force:",omitempty"`
	MaximumPermissionsLightningExperienceUser        bool   `force:",omitempty"`
	MaximumPermissionsListEmailSend                  bool   `force:",omitempty"`
	MaximumPermissionsLtngPromoReserved01UserPerm    bool   `force:",omitempty"`
	MaximumPermissionsManageAnalyticSnapshots        bool   `force:",omitempty"`
	MaximumPermissionsManageAuthProviders            bool   `force:",omitempty"`
	MaximumPermissionsManageBusinessHourHolidays     bool   `force:",omitempty"`
	MaximumPermissionsManageCallCenters              bool   `force:",omitempty"`
	MaximumPermissionsManageCases                    bool   `force:",omitempty"`
	MaximumPermissionsManageCategories               bool   `force:",omitempty"`
	MaximumPermissionsManageCertificates             bool   `force:",omitempty"`
	MaximumPermissionsManageChatterMessages          bool   `force:",omitempty"`
	MaximumPermissionsManageContentPermissions       bool   `force:",omitempty"`
	MaximumPermissionsManageContentProperties        bool   `force:",omitempty"`
	MaximumPermissionsManageContentTypes             bool   `force:",omitempty"`
	MaximumPermissionsManageCustomPermissions        bool   `force:",omitempty"`
	MaximumPermissionsManageCustomReportTypes        bool   `force:",omitempty"`
	MaximumPermissionsManageDashbdsInPubFolders      bool   `force:",omitempty"`
	MaximumPermissionsManageDataCategories           bool   `force:",omitempty"`
	MaximumPermissionsManageDataIntegrations         bool   `force:",omitempty"`
	MaximumPermissionsManageDynamicDashboards        bool   `force:",omitempty"`
	MaximumPermissionsManageEmailClientConfig        bool   `force:",omitempty"`
	MaximumPermissionsManageEncryptionKeys           bool   `force:",omitempty"`
	MaximumPermissionsManageExchangeConfig           bool   `force:",omitempty"`
	MaximumPermissionsManageHealthCheck              bool   `force:",omitempty"`
	MaximumPermissionsManageInteraction              bool   `force:",omitempty"`
	MaximumPermissionsManageInternalUsers            bool   `force:",omitempty"`
	MaximumPermissionsManageIpAddresses              bool   `force:",omitempty"`
	MaximumPermissionsManageKnowledge                bool   `force:",omitempty"`
	MaximumPermissionsManageKnowledgeImportExport    bool   `force:",omitempty"`
	MaximumPermissionsManageLeads                    bool   `force:",omitempty"`
	MaximumPermissionsManageLoginAccessPolicies      bool   `force:",omitempty"`
	MaximumPermissionsManageMobile                   bool   `force:",omitempty"`
	MaximumPermissionsManageNetworks                 bool   `force:",omitempty"`
	MaximumPermissionsManagePasswordPolicies         bool   `force:",omitempty"`
	MaximumPermissionsManageProfilesPermissionsets   bool   `force:",omitempty"`
	MaximumPermissionsManagePvtRptsAndDashbds        bool   `force:",omitempty"`
	MaximumPermissionsManageRemoteAccess             bool   `force:",omitempty"`
	MaximumPermissionsManageReportsInPubFolders      bool   `force:",omitempty"`
	MaximumPermissionsManageRoles                    bool   `force:",omitempty"`
	MaximumPermissionsManageSearchPromotionRules     bool   `force:",omitempty"`
	MaximumPermissionsManageSessionPermissionSets    bool   `force:",omitempty"`
	MaximumPermissionsManageSharing                  bool   `force:",omitempty"`
	MaximumPermissionsManageSolutions                bool   `force:",omitempty"`
	MaximumPermissionsManageSurveys                  bool   `force:",omitempty"`
	MaximumPermissionsManageSynonyms                 bool   `force:",omitempty"`
	MaximumPermissionsManageTemplatedApp             bool   `force:",omitempty"`
	MaximumPermissionsManageTwoFactor                bool   `force:",omitempty"`
	MaximumPermissionsManageUnlistedGroups           bool   `force:",omitempty"`
	MaximumPermissionsManageUsers                    bool   `force:",omitempty"`
	MaximumPermissionsMassInlineEdit                 bool   `force:",omitempty"`
	MaximumPermissionsMergeTopics                    bool   `force:",omitempty"`
	MaximumPermissionsModerateChatter                bool   `force:",omitempty"`
	MaximumPermissionsModerateNetworkUsers           bool   `force:",omitempty"`
	MaximumPermissionsModifyAllData                  bool   `force:",omitempty"`
	MaximumPermissionsModifyMetadata                 bool   `force:",omitempty"`
	MaximumPermissionsModifySecureAgents             bool   `force:",omitempty"`
	MaximumPermissionsNewReportBuilder               bool   `force:",omitempty"`
	MaximumPermissionsPackaging2                     bool   `force:",omitempty"`
	MaximumPermissionsPasswordNeverExpires           bool   `force:",omitempty"`
	MaximumPermissionsPreventClassicExperience       bool   `force:",omitempty"`
	MaximumPermissionsPublishPackaging               bool   `force:",omitempty"`
	MaximumPermissionsRemoveDirectMessageMembers     bool   `force:",omitempty"`
	MaximumPermissionsResetPasswords                 bool   `force:",omitempty"`
	MaximumPermissionsRunFlow                        bool   `force:",omitempty"`
	MaximumPermissionsRunReports                     bool   `force:",omitempty"`
	MaximumPermissionsSalesConsole                   bool   `force:",omitempty"`
	MaximumPermissionsScheduleReports                bool   `force:",omitempty"`
	MaximumPermissionsSelectFilesFromSalesforce      bool   `force:",omitempty"`
	MaximumPermissionsSendAnnouncementEmails         bool   `force:",omitempty"`
	MaximumPermissionsSendSitRequests                bool   `force:",omitempty"`
	MaximumPermissionsShareInternalArticles          bool   `force:",omitempty"`
	MaximumPermissionsShowCompanyNameAsUserBadge     bool   `force:",omitempty"`
	MaximumPermissionsSolutionImport                 bool   `force:",omitempty"`
	MaximumPermissionsStdAutomaticActivityCapture    bool   `force:",omitempty"`
	MaximumPermissionsSubmitMacrosAllowed            bool   `force:",omitempty"`
	MaximumPermissionsSubscribeDashboardToOtherUsers bool   `force:",omitempty"`
	MaximumPermissionsSubscribeReportToOtherUsers    bool   `force:",omitempty"`
	MaximumPermissionsSubscribeReportsRunAsUser      bool   `force:",omitempty"`
	MaximumPermissionsSubscribeToLightningDashboards bool   `force:",omitempty"`
	MaximumPermissionsSubscribeToLightningReports    bool   `force:",omitempty"`
	MaximumPermissionsTransferAnyCase                bool   `force:",omitempty"`
	MaximumPermissionsTransferAnyEntity              bool   `force:",omitempty"`
	MaximumPermissionsTransferAnyLead                bool   `force:",omitempty"`
	MaximumPermissionsTwoFactorApi                   bool   `force:",omitempty"`
	MaximumPermissionsUseTeamReassignWizards         bool   `force:",omitempty"`
	MaximumPermissionsUseTemplatedApp                bool   `force:",omitempty"`
	MaximumPermissionsUseWebLink                     bool   `force:",omitempty"`
	MaximumPermissionsViewAllActivities              bool   `force:",omitempty"`
	MaximumPermissionsViewAllData                    bool   `force:",omitempty"`
	MaximumPermissionsViewAllUsers                   bool   `force:",omitempty"`
	MaximumPermissionsViewContent                    bool   `force:",omitempty"`
	MaximumPermissionsViewDataAssessment             bool   `force:",omitempty"`
	MaximumPermissionsViewDataCategories             bool   `force:",omitempty"`
	MaximumPermissionsViewEncryptedData              bool   `force:",omitempty"`
	MaximumPermissionsViewEventLogFiles              bool   `force:",omitempty"`
	MaximumPermissionsViewHealthCheck                bool   `force:",omitempty"`
	MaximumPermissionsViewHelpLink                   bool   `force:",omitempty"`
	MaximumPermissionsViewMyTeamsDashboards          bool   `force:",omitempty"`
	MaximumPermissionsViewOnlyEmbeddedAppUser        bool   `force:",omitempty"`
	MaximumPermissionsViewPublicDashboards           bool   `force:",omitempty"`
	MaximumPermissionsViewPublicReports              bool   `force:",omitempty"`
	MaximumPermissionsViewRoles                      bool   `force:",omitempty"`
	MaximumPermissionsViewSetup                      bool   `force:",omitempty"`
	MaximumPermissionsWaveTabularDownload            bool   `force:",omitempty"`
	MaximumPermissionsWorkCalibrationUser            bool   `force:",omitempty"`
	MaximumPermissionsWorkDotComUserPerm             bool   `force:",omitempty"`
	PermissionSetLicenseKey                          string `force:",omitempty"`
	Status                                           string `force:",omitempty"`
	SystemModstamp                                   string `force:",omitempty"`
	TotalLicenses                                    int    `force:",omitempty"`
	UsedLicenses                                     int    `force:",omitempty"`
}

func (t *PermissionSetLicense) ApiName() string {
	return "PermissionSetLicense"
}

func (t *PermissionSetLicense) String() string {
	builder := strings.Builder{}
	builder.WriteString(fmt.Sprintf("PermissionSetLicense #%s - %s\n", t.Id, t.Name))
	builder.WriteString(fmt.Sprintf("\tCreatedById: %v\n", t.CreatedById))
	builder.WriteString(fmt.Sprintf("\tCreatedDate: %v\n", t.CreatedDate))
	builder.WriteString(fmt.Sprintf("\tDeveloperName: %v\n", t.DeveloperName))
	builder.WriteString(fmt.Sprintf("\tExpirationDate: %v\n", t.ExpirationDate))
	builder.WriteString(fmt.Sprintf("\tId: %v\n", t.Id))
	builder.WriteString(fmt.Sprintf("\tIsDeleted: %v\n", t.IsDeleted))
	builder.WriteString(fmt.Sprintf("\tLanguage: %v\n", t.Language))
	builder.WriteString(fmt.Sprintf("\tLastModifiedById: %v\n", t.LastModifiedById))
	builder.WriteString(fmt.Sprintf("\tLastModifiedDate: %v\n", t.LastModifiedDate))
	builder.WriteString(fmt.Sprintf("\tMasterLabel: %v\n", t.MasterLabel))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsAccessCMC: %v\n", t.MaximumPermissionsAccessCMC))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsActivateContract: %v\n", t.MaximumPermissionsActivateContract))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsActivateOrder: %v\n", t.MaximumPermissionsActivateOrder))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsAddAnalyticsRemoteConnections: %v\n", t.MaximumPermissionsAddAnalyticsRemoteConnections))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsAddDirectMessageMembers: %v\n", t.MaximumPermissionsAddDirectMessageMembers))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsAllowEmailIC: %v\n", t.MaximumPermissionsAllowEmailIC))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsAllowLightningLogin: %v\n", t.MaximumPermissionsAllowLightningLogin))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsAllowUniversalSearch: %v\n", t.MaximumPermissionsAllowUniversalSearch))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsAllowViewEditConvertedLeads: %v\n", t.MaximumPermissionsAllowViewEditConvertedLeads))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsAllowViewKnowledge: %v\n", t.MaximumPermissionsAllowViewKnowledge))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsApexRestServices: %v\n", t.MaximumPermissionsApexRestServices))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsApiEnabled: %v\n", t.MaximumPermissionsApiEnabled))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsAssignPermissionSets: %v\n", t.MaximumPermissionsAssignPermissionSets))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsAssignTopics: %v\n", t.MaximumPermissionsAssignTopics))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsAuthorApex: %v\n", t.MaximumPermissionsAuthorApex))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsAutomaticActivityCapture: %v\n", t.MaximumPermissionsAutomaticActivityCapture))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsBulkApiHardDelete: %v\n", t.MaximumPermissionsBulkApiHardDelete))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsBulkMacrosAllowed: %v\n", t.MaximumPermissionsBulkMacrosAllowed))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCampaignInfluence2: %v\n", t.MaximumPermissionsCampaignInfluence2))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCanApproveFeedPost: %v\n", t.MaximumPermissionsCanApproveFeedPost))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCanEditDataPrepRecipe: %v\n", t.MaximumPermissionsCanEditDataPrepRecipe))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCanInsertFeedSystemFields: %v\n", t.MaximumPermissionsCanInsertFeedSystemFields))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCanUseNewDashboardBuilder: %v\n", t.MaximumPermissionsCanUseNewDashboardBuilder))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCanVerifyComment: %v\n", t.MaximumPermissionsCanVerifyComment))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsChangeDashboardColors: %v\n", t.MaximumPermissionsChangeDashboardColors))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsChatterComposeUiCodesnippet: %v\n", t.MaximumPermissionsChatterComposeUiCodesnippet))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsChatterEditOwnPost: %v\n", t.MaximumPermissionsChatterEditOwnPost))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsChatterEditOwnRecordPost: %v\n", t.MaximumPermissionsChatterEditOwnRecordPost))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsChatterFileLink: %v\n", t.MaximumPermissionsChatterFileLink))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsChatterInternalUser: %v\n", t.MaximumPermissionsChatterInternalUser))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsChatterInviteExternalUsers: %v\n", t.MaximumPermissionsChatterInviteExternalUsers))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsChatterOwnGroups: %v\n", t.MaximumPermissionsChatterOwnGroups))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCloseConversations: %v\n", t.MaximumPermissionsCloseConversations))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsConfigCustomRecs: %v\n", t.MaximumPermissionsConfigCustomRecs))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsConnectOrgToEnvironmentHub: %v\n", t.MaximumPermissionsConnectOrgToEnvironmentHub))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsContentAdministrator: %v\n", t.MaximumPermissionsContentAdministrator))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsContentWorkspaces: %v\n", t.MaximumPermissionsContentWorkspaces))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsConvertLeads: %v\n", t.MaximumPermissionsConvertLeads))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCreateCustomizeDashboards: %v\n", t.MaximumPermissionsCreateCustomizeDashboards))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCreateCustomizeFilters: %v\n", t.MaximumPermissionsCreateCustomizeFilters))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCreateCustomizeReports: %v\n", t.MaximumPermissionsCreateCustomizeReports))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCreateDashboardFolders: %v\n", t.MaximumPermissionsCreateDashboardFolders))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCreatePackaging: %v\n", t.MaximumPermissionsCreatePackaging))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCreateReportFolders: %v\n", t.MaximumPermissionsCreateReportFolders))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCreateReportInLightning: %v\n", t.MaximumPermissionsCreateReportInLightning))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCreateTopics: %v\n", t.MaximumPermissionsCreateTopics))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCreateWorkspaces: %v\n", t.MaximumPermissionsCreateWorkspaces))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCustomMobileAppsAccess: %v\n", t.MaximumPermissionsCustomMobileAppsAccess))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCustomSidebarOnAllPages: %v\n", t.MaximumPermissionsCustomSidebarOnAllPages))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsCustomizeApplication: %v\n", t.MaximumPermissionsCustomizeApplication))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsDataExport: %v\n", t.MaximumPermissionsDataExport))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsDelegatedTwoFactor: %v\n", t.MaximumPermissionsDelegatedTwoFactor))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsDeleteActivatedContract: %v\n", t.MaximumPermissionsDeleteActivatedContract))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsDeleteTopics: %v\n", t.MaximumPermissionsDeleteTopics))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsDistributeFromPersWksp: %v\n", t.MaximumPermissionsDistributeFromPersWksp))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEditActivatedOrders: %v\n", t.MaximumPermissionsEditActivatedOrders))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEditBrandTemplates: %v\n", t.MaximumPermissionsEditBrandTemplates))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEditCaseComments: %v\n", t.MaximumPermissionsEditCaseComments))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEditEvent: %v\n", t.MaximumPermissionsEditEvent))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEditHtmlTemplates: %v\n", t.MaximumPermissionsEditHtmlTemplates))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEditKnowledge: %v\n", t.MaximumPermissionsEditKnowledge))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEditMyDashboards: %v\n", t.MaximumPermissionsEditMyDashboards))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEditMyReports: %v\n", t.MaximumPermissionsEditMyReports))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEditOppLineItemUnitPrice: %v\n", t.MaximumPermissionsEditOppLineItemUnitPrice))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEditPublicDocuments: %v\n", t.MaximumPermissionsEditPublicDocuments))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEditPublicFilters: %v\n", t.MaximumPermissionsEditPublicFilters))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEditPublicTemplates: %v\n", t.MaximumPermissionsEditPublicTemplates))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEditReadonlyFields: %v\n", t.MaximumPermissionsEditReadonlyFields))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEditTask: %v\n", t.MaximumPermissionsEditTask))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEditTopics: %v\n", t.MaximumPermissionsEditTopics))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEmailAdministration: %v\n", t.MaximumPermissionsEmailAdministration))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEmailMass: %v\n", t.MaximumPermissionsEmailMass))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEmailSingle: %v\n", t.MaximumPermissionsEmailSingle))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEmailTemplateManagement: %v\n", t.MaximumPermissionsEmailTemplateManagement))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEnableCommunityAppLauncher: %v\n", t.MaximumPermissionsEnableCommunityAppLauncher))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsEnableNotifications: %v\n", t.MaximumPermissionsEnableNotifications))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsExportReport: %v\n", t.MaximumPermissionsExportReport))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsFeedPinning: %v\n", t.MaximumPermissionsFeedPinning))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsFlowUFLRequired: %v\n", t.MaximumPermissionsFlowUFLRequired))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsForceTwoFactor: %v\n", t.MaximumPermissionsForceTwoFactor))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsGovernNetworks: %v\n", t.MaximumPermissionsGovernNetworks))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsHideReadByList: %v\n", t.MaximumPermissionsHideReadByList))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsIdentityConnect: %v\n", t.MaximumPermissionsIdentityConnect))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsIdentityEnabled: %v\n", t.MaximumPermissionsIdentityEnabled))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsImportCustomObjects: %v\n", t.MaximumPermissionsImportCustomObjects))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsImportLeads: %v\n", t.MaximumPermissionsImportLeads))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsImportPersonal: %v\n", t.MaximumPermissionsImportPersonal))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsInsightsAppAdmin: %v\n", t.MaximumPermissionsInsightsAppAdmin))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsInsightsAppDashboardEditor: %v\n", t.MaximumPermissionsInsightsAppDashboardEditor))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsInsightsAppEltEditor: %v\n", t.MaximumPermissionsInsightsAppEltEditor))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsInsightsAppUploadUser: %v\n", t.MaximumPermissionsInsightsAppUploadUser))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsInsightsAppUser: %v\n", t.MaximumPermissionsInsightsAppUser))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsInsightsCreateApplication: %v\n", t.MaximumPermissionsInsightsCreateApplication))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsInstallPackaging: %v\n", t.MaximumPermissionsInstallPackaging))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsIotUser: %v\n", t.MaximumPermissionsIotUser))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsLightningConsoleAllowedForUser: %v\n", t.MaximumPermissionsLightningConsoleAllowedForUser))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsLightningExperienceUser: %v\n", t.MaximumPermissionsLightningExperienceUser))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsListEmailSend: %v\n", t.MaximumPermissionsListEmailSend))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsLtngPromoReserved01UserPerm: %v\n", t.MaximumPermissionsLtngPromoReserved01UserPerm))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageAnalyticSnapshots: %v\n", t.MaximumPermissionsManageAnalyticSnapshots))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageAuthProviders: %v\n", t.MaximumPermissionsManageAuthProviders))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageBusinessHourHolidays: %v\n", t.MaximumPermissionsManageBusinessHourHolidays))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageCallCenters: %v\n", t.MaximumPermissionsManageCallCenters))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageCases: %v\n", t.MaximumPermissionsManageCases))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageCategories: %v\n", t.MaximumPermissionsManageCategories))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageCertificates: %v\n", t.MaximumPermissionsManageCertificates))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageChatterMessages: %v\n", t.MaximumPermissionsManageChatterMessages))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageContentPermissions: %v\n", t.MaximumPermissionsManageContentPermissions))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageContentProperties: %v\n", t.MaximumPermissionsManageContentProperties))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageContentTypes: %v\n", t.MaximumPermissionsManageContentTypes))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageCustomPermissions: %v\n", t.MaximumPermissionsManageCustomPermissions))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageCustomReportTypes: %v\n", t.MaximumPermissionsManageCustomReportTypes))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageDashbdsInPubFolders: %v\n", t.MaximumPermissionsManageDashbdsInPubFolders))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageDataCategories: %v\n", t.MaximumPermissionsManageDataCategories))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageDataIntegrations: %v\n", t.MaximumPermissionsManageDataIntegrations))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageDynamicDashboards: %v\n", t.MaximumPermissionsManageDynamicDashboards))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageEmailClientConfig: %v\n", t.MaximumPermissionsManageEmailClientConfig))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageEncryptionKeys: %v\n", t.MaximumPermissionsManageEncryptionKeys))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageExchangeConfig: %v\n", t.MaximumPermissionsManageExchangeConfig))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageHealthCheck: %v\n", t.MaximumPermissionsManageHealthCheck))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageInteraction: %v\n", t.MaximumPermissionsManageInteraction))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageInternalUsers: %v\n", t.MaximumPermissionsManageInternalUsers))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageIpAddresses: %v\n", t.MaximumPermissionsManageIpAddresses))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageKnowledge: %v\n", t.MaximumPermissionsManageKnowledge))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageKnowledgeImportExport: %v\n", t.MaximumPermissionsManageKnowledgeImportExport))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageLeads: %v\n", t.MaximumPermissionsManageLeads))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageLoginAccessPolicies: %v\n", t.MaximumPermissionsManageLoginAccessPolicies))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageMobile: %v\n", t.MaximumPermissionsManageMobile))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageNetworks: %v\n", t.MaximumPermissionsManageNetworks))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManagePasswordPolicies: %v\n", t.MaximumPermissionsManagePasswordPolicies))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageProfilesPermissionsets: %v\n", t.MaximumPermissionsManageProfilesPermissionsets))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManagePvtRptsAndDashbds: %v\n", t.MaximumPermissionsManagePvtRptsAndDashbds))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageRemoteAccess: %v\n", t.MaximumPermissionsManageRemoteAccess))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageReportsInPubFolders: %v\n", t.MaximumPermissionsManageReportsInPubFolders))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageRoles: %v\n", t.MaximumPermissionsManageRoles))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageSearchPromotionRules: %v\n", t.MaximumPermissionsManageSearchPromotionRules))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageSessionPermissionSets: %v\n", t.MaximumPermissionsManageSessionPermissionSets))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageSharing: %v\n", t.MaximumPermissionsManageSharing))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageSolutions: %v\n", t.MaximumPermissionsManageSolutions))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageSurveys: %v\n", t.MaximumPermissionsManageSurveys))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageSynonyms: %v\n", t.MaximumPermissionsManageSynonyms))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageTemplatedApp: %v\n", t.MaximumPermissionsManageTemplatedApp))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageTwoFactor: %v\n", t.MaximumPermissionsManageTwoFactor))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageUnlistedGroups: %v\n", t.MaximumPermissionsManageUnlistedGroups))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsManageUsers: %v\n", t.MaximumPermissionsManageUsers))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsMassInlineEdit: %v\n", t.MaximumPermissionsMassInlineEdit))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsMergeTopics: %v\n", t.MaximumPermissionsMergeTopics))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsModerateChatter: %v\n", t.MaximumPermissionsModerateChatter))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsModerateNetworkUsers: %v\n", t.MaximumPermissionsModerateNetworkUsers))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsModifyAllData: %v\n", t.MaximumPermissionsModifyAllData))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsModifyMetadata: %v\n", t.MaximumPermissionsModifyMetadata))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsModifySecureAgents: %v\n", t.MaximumPermissionsModifySecureAgents))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsNewReportBuilder: %v\n", t.MaximumPermissionsNewReportBuilder))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsPackaging2: %v\n", t.MaximumPermissionsPackaging2))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsPasswordNeverExpires: %v\n", t.MaximumPermissionsPasswordNeverExpires))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsPreventClassicExperience: %v\n", t.MaximumPermissionsPreventClassicExperience))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsPublishPackaging: %v\n", t.MaximumPermissionsPublishPackaging))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsRemoveDirectMessageMembers: %v\n", t.MaximumPermissionsRemoveDirectMessageMembers))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsResetPasswords: %v\n", t.MaximumPermissionsResetPasswords))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsRunFlow: %v\n", t.MaximumPermissionsRunFlow))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsRunReports: %v\n", t.MaximumPermissionsRunReports))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsSalesConsole: %v\n", t.MaximumPermissionsSalesConsole))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsScheduleReports: %v\n", t.MaximumPermissionsScheduleReports))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsSelectFilesFromSalesforce: %v\n", t.MaximumPermissionsSelectFilesFromSalesforce))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsSendAnnouncementEmails: %v\n", t.MaximumPermissionsSendAnnouncementEmails))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsSendSitRequests: %v\n", t.MaximumPermissionsSendSitRequests))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsShareInternalArticles: %v\n", t.MaximumPermissionsShareInternalArticles))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsShowCompanyNameAsUserBadge: %v\n", t.MaximumPermissionsShowCompanyNameAsUserBadge))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsSolutionImport: %v\n", t.MaximumPermissionsSolutionImport))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsStdAutomaticActivityCapture: %v\n", t.MaximumPermissionsStdAutomaticActivityCapture))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsSubmitMacrosAllowed: %v\n", t.MaximumPermissionsSubmitMacrosAllowed))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsSubscribeDashboardToOtherUsers: %v\n", t.MaximumPermissionsSubscribeDashboardToOtherUsers))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsSubscribeReportToOtherUsers: %v\n", t.MaximumPermissionsSubscribeReportToOtherUsers))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsSubscribeReportsRunAsUser: %v\n", t.MaximumPermissionsSubscribeReportsRunAsUser))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsSubscribeToLightningDashboards: %v\n", t.MaximumPermissionsSubscribeToLightningDashboards))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsSubscribeToLightningReports: %v\n", t.MaximumPermissionsSubscribeToLightningReports))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsTransferAnyCase: %v\n", t.MaximumPermissionsTransferAnyCase))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsTransferAnyEntity: %v\n", t.MaximumPermissionsTransferAnyEntity))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsTransferAnyLead: %v\n", t.MaximumPermissionsTransferAnyLead))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsTwoFactorApi: %v\n", t.MaximumPermissionsTwoFactorApi))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsUseTeamReassignWizards: %v\n", t.MaximumPermissionsUseTeamReassignWizards))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsUseTemplatedApp: %v\n", t.MaximumPermissionsUseTemplatedApp))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsUseWebLink: %v\n", t.MaximumPermissionsUseWebLink))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsViewAllActivities: %v\n", t.MaximumPermissionsViewAllActivities))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsViewAllData: %v\n", t.MaximumPermissionsViewAllData))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsViewAllUsers: %v\n", t.MaximumPermissionsViewAllUsers))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsViewContent: %v\n", t.MaximumPermissionsViewContent))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsViewDataAssessment: %v\n", t.MaximumPermissionsViewDataAssessment))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsViewDataCategories: %v\n", t.MaximumPermissionsViewDataCategories))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsViewEncryptedData: %v\n", t.MaximumPermissionsViewEncryptedData))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsViewEventLogFiles: %v\n", t.MaximumPermissionsViewEventLogFiles))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsViewHealthCheck: %v\n", t.MaximumPermissionsViewHealthCheck))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsViewHelpLink: %v\n", t.MaximumPermissionsViewHelpLink))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsViewMyTeamsDashboards: %v\n", t.MaximumPermissionsViewMyTeamsDashboards))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsViewOnlyEmbeddedAppUser: %v\n", t.MaximumPermissionsViewOnlyEmbeddedAppUser))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsViewPublicDashboards: %v\n", t.MaximumPermissionsViewPublicDashboards))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsViewPublicReports: %v\n", t.MaximumPermissionsViewPublicReports))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsViewRoles: %v\n", t.MaximumPermissionsViewRoles))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsViewSetup: %v\n", t.MaximumPermissionsViewSetup))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsWaveTabularDownload: %v\n", t.MaximumPermissionsWaveTabularDownload))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsWorkCalibrationUser: %v\n", t.MaximumPermissionsWorkCalibrationUser))
	builder.WriteString(fmt.Sprintf("\tMaximumPermissionsWorkDotComUserPerm: %v\n", t.MaximumPermissionsWorkDotComUserPerm))
	builder.WriteString(fmt.Sprintf("\tPermissionSetLicenseKey: %v\n", t.PermissionSetLicenseKey))
	builder.WriteString(fmt.Sprintf("\tStatus: %v\n", t.Status))
	builder.WriteString(fmt.Sprintf("\tSystemModstamp: %v\n", t.SystemModstamp))
	builder.WriteString(fmt.Sprintf("\tTotalLicenses: %v\n", t.TotalLicenses))
	builder.WriteString(fmt.Sprintf("\tUsedLicenses: %v\n", t.UsedLicenses))

	return builder.String()
}

type PermissionSetLicenseQueryResponse struct {
	BaseQuery
	Records []PermissionSetLicense `json:"Records" force:"records"`
}
