// This file was generated for SObject PermissionSet, API Version v43.0 at 2018-07-30 03:47:26.471961536 -0400 EDT m=+12.815048830

package sobjects

import (
	"fmt"
	"strings"
)

type PermissionSet struct {
	BaseSObject
	CreatedById                               string `force:",omitempty"`
	CreatedDate                               string `force:",omitempty"`
	Description                               string `force:",omitempty"`
	HasActivationRequired                     bool   `force:",omitempty"`
	Id                                        string `force:",omitempty"`
	IsCustom                                  bool   `force:",omitempty"`
	IsOwnedByProfile                          bool   `force:",omitempty"`
	Label                                     string `force:",omitempty"`
	LastModifiedById                          string `force:",omitempty"`
	LastModifiedDate                          string `force:",omitempty"`
	LicenseId                                 string `force:",omitempty"`
	Name                                      string `force:",omitempty"`
	NamespacePrefix                           string `force:",omitempty"`
	PermissionsAccessCMC                      bool   `force:",omitempty"`
	PermissionsActivateContract               bool   `force:",omitempty"`
	PermissionsActivateOrder                  bool   `force:",omitempty"`
	PermissionsAddAnalyticsRemoteConnections  bool   `force:",omitempty"`
	PermissionsAddDirectMessageMembers        bool   `force:",omitempty"`
	PermissionsAllowEmailIC                   bool   `force:",omitempty"`
	PermissionsAllowLightningLogin            bool   `force:",omitempty"`
	PermissionsAllowUniversalSearch           bool   `force:",omitempty"`
	PermissionsAllowViewEditConvertedLeads    bool   `force:",omitempty"`
	PermissionsAllowViewKnowledge             bool   `force:",omitempty"`
	PermissionsApexRestServices               bool   `force:",omitempty"`
	PermissionsApiEnabled                     bool   `force:",omitempty"`
	PermissionsAssignPermissionSets           bool   `force:",omitempty"`
	PermissionsAssignTopics                   bool   `force:",omitempty"`
	PermissionsAuthorApex                     bool   `force:",omitempty"`
	PermissionsAutomaticActivityCapture       bool   `force:",omitempty"`
	PermissionsBulkApiHardDelete              bool   `force:",omitempty"`
	PermissionsBulkMacrosAllowed              bool   `force:",omitempty"`
	PermissionsCampaignInfluence2             bool   `force:",omitempty"`
	PermissionsCanApproveFeedPost             bool   `force:",omitempty"`
	PermissionsCanEditDataPrepRecipe          bool   `force:",omitempty"`
	PermissionsCanInsertFeedSystemFields      bool   `force:",omitempty"`
	PermissionsCanUseNewDashboardBuilder      bool   `force:",omitempty"`
	PermissionsCanVerifyComment               bool   `force:",omitempty"`
	PermissionsChangeDashboardColors          bool   `force:",omitempty"`
	PermissionsChatterComposeUiCodesnippet    bool   `force:",omitempty"`
	PermissionsChatterEditOwnPost             bool   `force:",omitempty"`
	PermissionsChatterEditOwnRecordPost       bool   `force:",omitempty"`
	PermissionsChatterFileLink                bool   `force:",omitempty"`
	PermissionsChatterInternalUser            bool   `force:",omitempty"`
	PermissionsChatterInviteExternalUsers     bool   `force:",omitempty"`
	PermissionsChatterOwnGroups               bool   `force:",omitempty"`
	PermissionsCloseConversations             bool   `force:",omitempty"`
	PermissionsConfigCustomRecs               bool   `force:",omitempty"`
	PermissionsConnectOrgToEnvironmentHub     bool   `force:",omitempty"`
	PermissionsContentAdministrator           bool   `force:",omitempty"`
	PermissionsContentWorkspaces              bool   `force:",omitempty"`
	PermissionsConvertLeads                   bool   `force:",omitempty"`
	PermissionsCreateCustomizeDashboards      bool   `force:",omitempty"`
	PermissionsCreateCustomizeFilters         bool   `force:",omitempty"`
	PermissionsCreateCustomizeReports         bool   `force:",omitempty"`
	PermissionsCreateDashboardFolders         bool   `force:",omitempty"`
	PermissionsCreatePackaging                bool   `force:",omitempty"`
	PermissionsCreateReportFolders            bool   `force:",omitempty"`
	PermissionsCreateReportInLightning        bool   `force:",omitempty"`
	PermissionsCreateTopics                   bool   `force:",omitempty"`
	PermissionsCreateWorkspaces               bool   `force:",omitempty"`
	PermissionsCustomMobileAppsAccess         bool   `force:",omitempty"`
	PermissionsCustomSidebarOnAllPages        bool   `force:",omitempty"`
	PermissionsCustomizeApplication           bool   `force:",omitempty"`
	PermissionsDataExport                     bool   `force:",omitempty"`
	PermissionsDelegatedTwoFactor             bool   `force:",omitempty"`
	PermissionsDeleteActivatedContract        bool   `force:",omitempty"`
	PermissionsDeleteTopics                   bool   `force:",omitempty"`
	PermissionsDistributeFromPersWksp         bool   `force:",omitempty"`
	PermissionsEditActivatedOrders            bool   `force:",omitempty"`
	PermissionsEditBrandTemplates             bool   `force:",omitempty"`
	PermissionsEditCaseComments               bool   `force:",omitempty"`
	PermissionsEditEvent                      bool   `force:",omitempty"`
	PermissionsEditHtmlTemplates              bool   `force:",omitempty"`
	PermissionsEditKnowledge                  bool   `force:",omitempty"`
	PermissionsEditMyDashboards               bool   `force:",omitempty"`
	PermissionsEditMyReports                  bool   `force:",omitempty"`
	PermissionsEditOppLineItemUnitPrice       bool   `force:",omitempty"`
	PermissionsEditPublicDocuments            bool   `force:",omitempty"`
	PermissionsEditPublicFilters              bool   `force:",omitempty"`
	PermissionsEditPublicTemplates            bool   `force:",omitempty"`
	PermissionsEditReadonlyFields             bool   `force:",omitempty"`
	PermissionsEditTask                       bool   `force:",omitempty"`
	PermissionsEditTopics                     bool   `force:",omitempty"`
	PermissionsEmailAdministration            bool   `force:",omitempty"`
	PermissionsEmailMass                      bool   `force:",omitempty"`
	PermissionsEmailSingle                    bool   `force:",omitempty"`
	PermissionsEmailTemplateManagement        bool   `force:",omitempty"`
	PermissionsEnableCommunityAppLauncher     bool   `force:",omitempty"`
	PermissionsEnableNotifications            bool   `force:",omitempty"`
	PermissionsExportReport                   bool   `force:",omitempty"`
	PermissionsFeedPinning                    bool   `force:",omitempty"`
	PermissionsFlowUFLRequired                bool   `force:",omitempty"`
	PermissionsForceTwoFactor                 bool   `force:",omitempty"`
	PermissionsGovernNetworks                 bool   `force:",omitempty"`
	PermissionsHideReadByList                 bool   `force:",omitempty"`
	PermissionsIdentityConnect                bool   `force:",omitempty"`
	PermissionsIdentityEnabled                bool   `force:",omitempty"`
	PermissionsImportCustomObjects            bool   `force:",omitempty"`
	PermissionsImportLeads                    bool   `force:",omitempty"`
	PermissionsImportPersonal                 bool   `force:",omitempty"`
	PermissionsInsightsAppAdmin               bool   `force:",omitempty"`
	PermissionsInsightsAppDashboardEditor     bool   `force:",omitempty"`
	PermissionsInsightsAppEltEditor           bool   `force:",omitempty"`
	PermissionsInsightsAppUploadUser          bool   `force:",omitempty"`
	PermissionsInsightsAppUser                bool   `force:",omitempty"`
	PermissionsInsightsCreateApplication      bool   `force:",omitempty"`
	PermissionsInstallPackaging               bool   `force:",omitempty"`
	PermissionsIotUser                        bool   `force:",omitempty"`
	PermissionsLightningConsoleAllowedForUser bool   `force:",omitempty"`
	PermissionsLightningExperienceUser        bool   `force:",omitempty"`
	PermissionsListEmailSend                  bool   `force:",omitempty"`
	PermissionsLtngPromoReserved01UserPerm    bool   `force:",omitempty"`
	PermissionsManageAnalyticSnapshots        bool   `force:",omitempty"`
	PermissionsManageAuthProviders            bool   `force:",omitempty"`
	PermissionsManageBusinessHourHolidays     bool   `force:",omitempty"`
	PermissionsManageCallCenters              bool   `force:",omitempty"`
	PermissionsManageCases                    bool   `force:",omitempty"`
	PermissionsManageCategories               bool   `force:",omitempty"`
	PermissionsManageCertificates             bool   `force:",omitempty"`
	PermissionsManageChatterMessages          bool   `force:",omitempty"`
	PermissionsManageContentPermissions       bool   `force:",omitempty"`
	PermissionsManageContentProperties        bool   `force:",omitempty"`
	PermissionsManageContentTypes             bool   `force:",omitempty"`
	PermissionsManageCustomPermissions        bool   `force:",omitempty"`
	PermissionsManageCustomReportTypes        bool   `force:",omitempty"`
	PermissionsManageDashbdsInPubFolders      bool   `force:",omitempty"`
	PermissionsManageDataCategories           bool   `force:",omitempty"`
	PermissionsManageDataIntegrations         bool   `force:",omitempty"`
	PermissionsManageDynamicDashboards        bool   `force:",omitempty"`
	PermissionsManageEmailClientConfig        bool   `force:",omitempty"`
	PermissionsManageEncryptionKeys           bool   `force:",omitempty"`
	PermissionsManageExchangeConfig           bool   `force:",omitempty"`
	PermissionsManageHealthCheck              bool   `force:",omitempty"`
	PermissionsManageInteraction              bool   `force:",omitempty"`
	PermissionsManageInternalUsers            bool   `force:",omitempty"`
	PermissionsManageIpAddresses              bool   `force:",omitempty"`
	PermissionsManageKnowledge                bool   `force:",omitempty"`
	PermissionsManageKnowledgeImportExport    bool   `force:",omitempty"`
	PermissionsManageLeads                    bool   `force:",omitempty"`
	PermissionsManageLoginAccessPolicies      bool   `force:",omitempty"`
	PermissionsManageMobile                   bool   `force:",omitempty"`
	PermissionsManageNetworks                 bool   `force:",omitempty"`
	PermissionsManagePasswordPolicies         bool   `force:",omitempty"`
	PermissionsManageProfilesPermissionsets   bool   `force:",omitempty"`
	PermissionsManagePvtRptsAndDashbds        bool   `force:",omitempty"`
	PermissionsManageRemoteAccess             bool   `force:",omitempty"`
	PermissionsManageReportsInPubFolders      bool   `force:",omitempty"`
	PermissionsManageRoles                    bool   `force:",omitempty"`
	PermissionsManageSearchPromotionRules     bool   `force:",omitempty"`
	PermissionsManageSessionPermissionSets    bool   `force:",omitempty"`
	PermissionsManageSharing                  bool   `force:",omitempty"`
	PermissionsManageSolutions                bool   `force:",omitempty"`
	PermissionsManageSurveys                  bool   `force:",omitempty"`
	PermissionsManageSynonyms                 bool   `force:",omitempty"`
	PermissionsManageTemplatedApp             bool   `force:",omitempty"`
	PermissionsManageTwoFactor                bool   `force:",omitempty"`
	PermissionsManageUnlistedGroups           bool   `force:",omitempty"`
	PermissionsManageUsers                    bool   `force:",omitempty"`
	PermissionsMassInlineEdit                 bool   `force:",omitempty"`
	PermissionsMergeTopics                    bool   `force:",omitempty"`
	PermissionsModerateChatter                bool   `force:",omitempty"`
	PermissionsModerateNetworkUsers           bool   `force:",omitempty"`
	PermissionsModifyAllData                  bool   `force:",omitempty"`
	PermissionsModifyMetadata                 bool   `force:",omitempty"`
	PermissionsModifySecureAgents             bool   `force:",omitempty"`
	PermissionsNewReportBuilder               bool   `force:",omitempty"`
	PermissionsPackaging2                     bool   `force:",omitempty"`
	PermissionsPasswordNeverExpires           bool   `force:",omitempty"`
	PermissionsPreventClassicExperience       bool   `force:",omitempty"`
	PermissionsPublishPackaging               bool   `force:",omitempty"`
	PermissionsRemoveDirectMessageMembers     bool   `force:",omitempty"`
	PermissionsResetPasswords                 bool   `force:",omitempty"`
	PermissionsRunFlow                        bool   `force:",omitempty"`
	PermissionsRunReports                     bool   `force:",omitempty"`
	PermissionsSalesConsole                   bool   `force:",omitempty"`
	PermissionsScheduleReports                bool   `force:",omitempty"`
	PermissionsSelectFilesFromSalesforce      bool   `force:",omitempty"`
	PermissionsSendAnnouncementEmails         bool   `force:",omitempty"`
	PermissionsSendSitRequests                bool   `force:",omitempty"`
	PermissionsShareInternalArticles          bool   `force:",omitempty"`
	PermissionsShowCompanyNameAsUserBadge     bool   `force:",omitempty"`
	PermissionsSolutionImport                 bool   `force:",omitempty"`
	PermissionsStdAutomaticActivityCapture    bool   `force:",omitempty"`
	PermissionsSubmitMacrosAllowed            bool   `force:",omitempty"`
	PermissionsSubscribeDashboardToOtherUsers bool   `force:",omitempty"`
	PermissionsSubscribeReportToOtherUsers    bool   `force:",omitempty"`
	PermissionsSubscribeReportsRunAsUser      bool   `force:",omitempty"`
	PermissionsSubscribeToLightningDashboards bool   `force:",omitempty"`
	PermissionsSubscribeToLightningReports    bool   `force:",omitempty"`
	PermissionsTransferAnyCase                bool   `force:",omitempty"`
	PermissionsTransferAnyEntity              bool   `force:",omitempty"`
	PermissionsTransferAnyLead                bool   `force:",omitempty"`
	PermissionsTwoFactorApi                   bool   `force:",omitempty"`
	PermissionsUseTeamReassignWizards         bool   `force:",omitempty"`
	PermissionsUseTemplatedApp                bool   `force:",omitempty"`
	PermissionsUseWebLink                     bool   `force:",omitempty"`
	PermissionsViewAllActivities              bool   `force:",omitempty"`
	PermissionsViewAllData                    bool   `force:",omitempty"`
	PermissionsViewAllUsers                   bool   `force:",omitempty"`
	PermissionsViewContent                    bool   `force:",omitempty"`
	PermissionsViewDataAssessment             bool   `force:",omitempty"`
	PermissionsViewDataCategories             bool   `force:",omitempty"`
	PermissionsViewEncryptedData              bool   `force:",omitempty"`
	PermissionsViewEventLogFiles              bool   `force:",omitempty"`
	PermissionsViewHealthCheck                bool   `force:",omitempty"`
	PermissionsViewHelpLink                   bool   `force:",omitempty"`
	PermissionsViewMyTeamsDashboards          bool   `force:",omitempty"`
	PermissionsViewOnlyEmbeddedAppUser        bool   `force:",omitempty"`
	PermissionsViewPublicDashboards           bool   `force:",omitempty"`
	PermissionsViewPublicReports              bool   `force:",omitempty"`
	PermissionsViewRoles                      bool   `force:",omitempty"`
	PermissionsViewSetup                      bool   `force:",omitempty"`
	PermissionsWaveTabularDownload            bool   `force:",omitempty"`
	PermissionsWorkCalibrationUser            bool   `force:",omitempty"`
	PermissionsWorkDotComUserPerm             bool   `force:",omitempty"`
	ProfileId                                 string `force:",omitempty"`
	SystemModstamp                            string `force:",omitempty"`
}

func (t *PermissionSet) ApiName() string {
	return "PermissionSet"
}

func (t *PermissionSet) String() string {
	builder := strings.Builder{}
	builder.WriteString(fmt.Sprintf("PermissionSet #%s - %s\n", t.Id, t.Name))
	builder.WriteString(fmt.Sprintf("\tCreatedById: %v\n", t.CreatedById))
	builder.WriteString(fmt.Sprintf("\tCreatedDate: %v\n", t.CreatedDate))
	builder.WriteString(fmt.Sprintf("\tDescription: %v\n", t.Description))
	builder.WriteString(fmt.Sprintf("\tHasActivationRequired: %v\n", t.HasActivationRequired))
	builder.WriteString(fmt.Sprintf("\tId: %v\n", t.Id))
	builder.WriteString(fmt.Sprintf("\tIsCustom: %v\n", t.IsCustom))
	builder.WriteString(fmt.Sprintf("\tIsOwnedByProfile: %v\n", t.IsOwnedByProfile))
	builder.WriteString(fmt.Sprintf("\tLabel: %v\n", t.Label))
	builder.WriteString(fmt.Sprintf("\tLastModifiedById: %v\n", t.LastModifiedById))
	builder.WriteString(fmt.Sprintf("\tLastModifiedDate: %v\n", t.LastModifiedDate))
	builder.WriteString(fmt.Sprintf("\tLicenseId: %v\n", t.LicenseId))
	builder.WriteString(fmt.Sprintf("\tName: %v\n", t.Name))
	builder.WriteString(fmt.Sprintf("\tNamespacePrefix: %v\n", t.NamespacePrefix))
	builder.WriteString(fmt.Sprintf("\tPermissionsAccessCMC: %v\n", t.PermissionsAccessCMC))
	builder.WriteString(fmt.Sprintf("\tPermissionsActivateContract: %v\n", t.PermissionsActivateContract))
	builder.WriteString(fmt.Sprintf("\tPermissionsActivateOrder: %v\n", t.PermissionsActivateOrder))
	builder.WriteString(fmt.Sprintf("\tPermissionsAddAnalyticsRemoteConnections: %v\n", t.PermissionsAddAnalyticsRemoteConnections))
	builder.WriteString(fmt.Sprintf("\tPermissionsAddDirectMessageMembers: %v\n", t.PermissionsAddDirectMessageMembers))
	builder.WriteString(fmt.Sprintf("\tPermissionsAllowEmailIC: %v\n", t.PermissionsAllowEmailIC))
	builder.WriteString(fmt.Sprintf("\tPermissionsAllowLightningLogin: %v\n", t.PermissionsAllowLightningLogin))
	builder.WriteString(fmt.Sprintf("\tPermissionsAllowUniversalSearch: %v\n", t.PermissionsAllowUniversalSearch))
	builder.WriteString(fmt.Sprintf("\tPermissionsAllowViewEditConvertedLeads: %v\n", t.PermissionsAllowViewEditConvertedLeads))
	builder.WriteString(fmt.Sprintf("\tPermissionsAllowViewKnowledge: %v\n", t.PermissionsAllowViewKnowledge))
	builder.WriteString(fmt.Sprintf("\tPermissionsApexRestServices: %v\n", t.PermissionsApexRestServices))
	builder.WriteString(fmt.Sprintf("\tPermissionsApiEnabled: %v\n", t.PermissionsApiEnabled))
	builder.WriteString(fmt.Sprintf("\tPermissionsAssignPermissionSets: %v\n", t.PermissionsAssignPermissionSets))
	builder.WriteString(fmt.Sprintf("\tPermissionsAssignTopics: %v\n", t.PermissionsAssignTopics))
	builder.WriteString(fmt.Sprintf("\tPermissionsAuthorApex: %v\n", t.PermissionsAuthorApex))
	builder.WriteString(fmt.Sprintf("\tPermissionsAutomaticActivityCapture: %v\n", t.PermissionsAutomaticActivityCapture))
	builder.WriteString(fmt.Sprintf("\tPermissionsBulkApiHardDelete: %v\n", t.PermissionsBulkApiHardDelete))
	builder.WriteString(fmt.Sprintf("\tPermissionsBulkMacrosAllowed: %v\n", t.PermissionsBulkMacrosAllowed))
	builder.WriteString(fmt.Sprintf("\tPermissionsCampaignInfluence2: %v\n", t.PermissionsCampaignInfluence2))
	builder.WriteString(fmt.Sprintf("\tPermissionsCanApproveFeedPost: %v\n", t.PermissionsCanApproveFeedPost))
	builder.WriteString(fmt.Sprintf("\tPermissionsCanEditDataPrepRecipe: %v\n", t.PermissionsCanEditDataPrepRecipe))
	builder.WriteString(fmt.Sprintf("\tPermissionsCanInsertFeedSystemFields: %v\n", t.PermissionsCanInsertFeedSystemFields))
	builder.WriteString(fmt.Sprintf("\tPermissionsCanUseNewDashboardBuilder: %v\n", t.PermissionsCanUseNewDashboardBuilder))
	builder.WriteString(fmt.Sprintf("\tPermissionsCanVerifyComment: %v\n", t.PermissionsCanVerifyComment))
	builder.WriteString(fmt.Sprintf("\tPermissionsChangeDashboardColors: %v\n", t.PermissionsChangeDashboardColors))
	builder.WriteString(fmt.Sprintf("\tPermissionsChatterComposeUiCodesnippet: %v\n", t.PermissionsChatterComposeUiCodesnippet))
	builder.WriteString(fmt.Sprintf("\tPermissionsChatterEditOwnPost: %v\n", t.PermissionsChatterEditOwnPost))
	builder.WriteString(fmt.Sprintf("\tPermissionsChatterEditOwnRecordPost: %v\n", t.PermissionsChatterEditOwnRecordPost))
	builder.WriteString(fmt.Sprintf("\tPermissionsChatterFileLink: %v\n", t.PermissionsChatterFileLink))
	builder.WriteString(fmt.Sprintf("\tPermissionsChatterInternalUser: %v\n", t.PermissionsChatterInternalUser))
	builder.WriteString(fmt.Sprintf("\tPermissionsChatterInviteExternalUsers: %v\n", t.PermissionsChatterInviteExternalUsers))
	builder.WriteString(fmt.Sprintf("\tPermissionsChatterOwnGroups: %v\n", t.PermissionsChatterOwnGroups))
	builder.WriteString(fmt.Sprintf("\tPermissionsCloseConversations: %v\n", t.PermissionsCloseConversations))
	builder.WriteString(fmt.Sprintf("\tPermissionsConfigCustomRecs: %v\n", t.PermissionsConfigCustomRecs))
	builder.WriteString(fmt.Sprintf("\tPermissionsConnectOrgToEnvironmentHub: %v\n", t.PermissionsConnectOrgToEnvironmentHub))
	builder.WriteString(fmt.Sprintf("\tPermissionsContentAdministrator: %v\n", t.PermissionsContentAdministrator))
	builder.WriteString(fmt.Sprintf("\tPermissionsContentWorkspaces: %v\n", t.PermissionsContentWorkspaces))
	builder.WriteString(fmt.Sprintf("\tPermissionsConvertLeads: %v\n", t.PermissionsConvertLeads))
	builder.WriteString(fmt.Sprintf("\tPermissionsCreateCustomizeDashboards: %v\n", t.PermissionsCreateCustomizeDashboards))
	builder.WriteString(fmt.Sprintf("\tPermissionsCreateCustomizeFilters: %v\n", t.PermissionsCreateCustomizeFilters))
	builder.WriteString(fmt.Sprintf("\tPermissionsCreateCustomizeReports: %v\n", t.PermissionsCreateCustomizeReports))
	builder.WriteString(fmt.Sprintf("\tPermissionsCreateDashboardFolders: %v\n", t.PermissionsCreateDashboardFolders))
	builder.WriteString(fmt.Sprintf("\tPermissionsCreatePackaging: %v\n", t.PermissionsCreatePackaging))
	builder.WriteString(fmt.Sprintf("\tPermissionsCreateReportFolders: %v\n", t.PermissionsCreateReportFolders))
	builder.WriteString(fmt.Sprintf("\tPermissionsCreateReportInLightning: %v\n", t.PermissionsCreateReportInLightning))
	builder.WriteString(fmt.Sprintf("\tPermissionsCreateTopics: %v\n", t.PermissionsCreateTopics))
	builder.WriteString(fmt.Sprintf("\tPermissionsCreateWorkspaces: %v\n", t.PermissionsCreateWorkspaces))
	builder.WriteString(fmt.Sprintf("\tPermissionsCustomMobileAppsAccess: %v\n", t.PermissionsCustomMobileAppsAccess))
	builder.WriteString(fmt.Sprintf("\tPermissionsCustomSidebarOnAllPages: %v\n", t.PermissionsCustomSidebarOnAllPages))
	builder.WriteString(fmt.Sprintf("\tPermissionsCustomizeApplication: %v\n", t.PermissionsCustomizeApplication))
	builder.WriteString(fmt.Sprintf("\tPermissionsDataExport: %v\n", t.PermissionsDataExport))
	builder.WriteString(fmt.Sprintf("\tPermissionsDelegatedTwoFactor: %v\n", t.PermissionsDelegatedTwoFactor))
	builder.WriteString(fmt.Sprintf("\tPermissionsDeleteActivatedContract: %v\n", t.PermissionsDeleteActivatedContract))
	builder.WriteString(fmt.Sprintf("\tPermissionsDeleteTopics: %v\n", t.PermissionsDeleteTopics))
	builder.WriteString(fmt.Sprintf("\tPermissionsDistributeFromPersWksp: %v\n", t.PermissionsDistributeFromPersWksp))
	builder.WriteString(fmt.Sprintf("\tPermissionsEditActivatedOrders: %v\n", t.PermissionsEditActivatedOrders))
	builder.WriteString(fmt.Sprintf("\tPermissionsEditBrandTemplates: %v\n", t.PermissionsEditBrandTemplates))
	builder.WriteString(fmt.Sprintf("\tPermissionsEditCaseComments: %v\n", t.PermissionsEditCaseComments))
	builder.WriteString(fmt.Sprintf("\tPermissionsEditEvent: %v\n", t.PermissionsEditEvent))
	builder.WriteString(fmt.Sprintf("\tPermissionsEditHtmlTemplates: %v\n", t.PermissionsEditHtmlTemplates))
	builder.WriteString(fmt.Sprintf("\tPermissionsEditKnowledge: %v\n", t.PermissionsEditKnowledge))
	builder.WriteString(fmt.Sprintf("\tPermissionsEditMyDashboards: %v\n", t.PermissionsEditMyDashboards))
	builder.WriteString(fmt.Sprintf("\tPermissionsEditMyReports: %v\n", t.PermissionsEditMyReports))
	builder.WriteString(fmt.Sprintf("\tPermissionsEditOppLineItemUnitPrice: %v\n", t.PermissionsEditOppLineItemUnitPrice))
	builder.WriteString(fmt.Sprintf("\tPermissionsEditPublicDocuments: %v\n", t.PermissionsEditPublicDocuments))
	builder.WriteString(fmt.Sprintf("\tPermissionsEditPublicFilters: %v\n", t.PermissionsEditPublicFilters))
	builder.WriteString(fmt.Sprintf("\tPermissionsEditPublicTemplates: %v\n", t.PermissionsEditPublicTemplates))
	builder.WriteString(fmt.Sprintf("\tPermissionsEditReadonlyFields: %v\n", t.PermissionsEditReadonlyFields))
	builder.WriteString(fmt.Sprintf("\tPermissionsEditTask: %v\n", t.PermissionsEditTask))
	builder.WriteString(fmt.Sprintf("\tPermissionsEditTopics: %v\n", t.PermissionsEditTopics))
	builder.WriteString(fmt.Sprintf("\tPermissionsEmailAdministration: %v\n", t.PermissionsEmailAdministration))
	builder.WriteString(fmt.Sprintf("\tPermissionsEmailMass: %v\n", t.PermissionsEmailMass))
	builder.WriteString(fmt.Sprintf("\tPermissionsEmailSingle: %v\n", t.PermissionsEmailSingle))
	builder.WriteString(fmt.Sprintf("\tPermissionsEmailTemplateManagement: %v\n", t.PermissionsEmailTemplateManagement))
	builder.WriteString(fmt.Sprintf("\tPermissionsEnableCommunityAppLauncher: %v\n", t.PermissionsEnableCommunityAppLauncher))
	builder.WriteString(fmt.Sprintf("\tPermissionsEnableNotifications: %v\n", t.PermissionsEnableNotifications))
	builder.WriteString(fmt.Sprintf("\tPermissionsExportReport: %v\n", t.PermissionsExportReport))
	builder.WriteString(fmt.Sprintf("\tPermissionsFeedPinning: %v\n", t.PermissionsFeedPinning))
	builder.WriteString(fmt.Sprintf("\tPermissionsFlowUFLRequired: %v\n", t.PermissionsFlowUFLRequired))
	builder.WriteString(fmt.Sprintf("\tPermissionsForceTwoFactor: %v\n", t.PermissionsForceTwoFactor))
	builder.WriteString(fmt.Sprintf("\tPermissionsGovernNetworks: %v\n", t.PermissionsGovernNetworks))
	builder.WriteString(fmt.Sprintf("\tPermissionsHideReadByList: %v\n", t.PermissionsHideReadByList))
	builder.WriteString(fmt.Sprintf("\tPermissionsIdentityConnect: %v\n", t.PermissionsIdentityConnect))
	builder.WriteString(fmt.Sprintf("\tPermissionsIdentityEnabled: %v\n", t.PermissionsIdentityEnabled))
	builder.WriteString(fmt.Sprintf("\tPermissionsImportCustomObjects: %v\n", t.PermissionsImportCustomObjects))
	builder.WriteString(fmt.Sprintf("\tPermissionsImportLeads: %v\n", t.PermissionsImportLeads))
	builder.WriteString(fmt.Sprintf("\tPermissionsImportPersonal: %v\n", t.PermissionsImportPersonal))
	builder.WriteString(fmt.Sprintf("\tPermissionsInsightsAppAdmin: %v\n", t.PermissionsInsightsAppAdmin))
	builder.WriteString(fmt.Sprintf("\tPermissionsInsightsAppDashboardEditor: %v\n", t.PermissionsInsightsAppDashboardEditor))
	builder.WriteString(fmt.Sprintf("\tPermissionsInsightsAppEltEditor: %v\n", t.PermissionsInsightsAppEltEditor))
	builder.WriteString(fmt.Sprintf("\tPermissionsInsightsAppUploadUser: %v\n", t.PermissionsInsightsAppUploadUser))
	builder.WriteString(fmt.Sprintf("\tPermissionsInsightsAppUser: %v\n", t.PermissionsInsightsAppUser))
	builder.WriteString(fmt.Sprintf("\tPermissionsInsightsCreateApplication: %v\n", t.PermissionsInsightsCreateApplication))
	builder.WriteString(fmt.Sprintf("\tPermissionsInstallPackaging: %v\n", t.PermissionsInstallPackaging))
	builder.WriteString(fmt.Sprintf("\tPermissionsIotUser: %v\n", t.PermissionsIotUser))
	builder.WriteString(fmt.Sprintf("\tPermissionsLightningConsoleAllowedForUser: %v\n", t.PermissionsLightningConsoleAllowedForUser))
	builder.WriteString(fmt.Sprintf("\tPermissionsLightningExperienceUser: %v\n", t.PermissionsLightningExperienceUser))
	builder.WriteString(fmt.Sprintf("\tPermissionsListEmailSend: %v\n", t.PermissionsListEmailSend))
	builder.WriteString(fmt.Sprintf("\tPermissionsLtngPromoReserved01UserPerm: %v\n", t.PermissionsLtngPromoReserved01UserPerm))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageAnalyticSnapshots: %v\n", t.PermissionsManageAnalyticSnapshots))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageAuthProviders: %v\n", t.PermissionsManageAuthProviders))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageBusinessHourHolidays: %v\n", t.PermissionsManageBusinessHourHolidays))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageCallCenters: %v\n", t.PermissionsManageCallCenters))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageCases: %v\n", t.PermissionsManageCases))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageCategories: %v\n", t.PermissionsManageCategories))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageCertificates: %v\n", t.PermissionsManageCertificates))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageChatterMessages: %v\n", t.PermissionsManageChatterMessages))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageContentPermissions: %v\n", t.PermissionsManageContentPermissions))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageContentProperties: %v\n", t.PermissionsManageContentProperties))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageContentTypes: %v\n", t.PermissionsManageContentTypes))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageCustomPermissions: %v\n", t.PermissionsManageCustomPermissions))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageCustomReportTypes: %v\n", t.PermissionsManageCustomReportTypes))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageDashbdsInPubFolders: %v\n", t.PermissionsManageDashbdsInPubFolders))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageDataCategories: %v\n", t.PermissionsManageDataCategories))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageDataIntegrations: %v\n", t.PermissionsManageDataIntegrations))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageDynamicDashboards: %v\n", t.PermissionsManageDynamicDashboards))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageEmailClientConfig: %v\n", t.PermissionsManageEmailClientConfig))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageEncryptionKeys: %v\n", t.PermissionsManageEncryptionKeys))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageExchangeConfig: %v\n", t.PermissionsManageExchangeConfig))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageHealthCheck: %v\n", t.PermissionsManageHealthCheck))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageInteraction: %v\n", t.PermissionsManageInteraction))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageInternalUsers: %v\n", t.PermissionsManageInternalUsers))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageIpAddresses: %v\n", t.PermissionsManageIpAddresses))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageKnowledge: %v\n", t.PermissionsManageKnowledge))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageKnowledgeImportExport: %v\n", t.PermissionsManageKnowledgeImportExport))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageLeads: %v\n", t.PermissionsManageLeads))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageLoginAccessPolicies: %v\n", t.PermissionsManageLoginAccessPolicies))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageMobile: %v\n", t.PermissionsManageMobile))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageNetworks: %v\n", t.PermissionsManageNetworks))
	builder.WriteString(fmt.Sprintf("\tPermissionsManagePasswordPolicies: %v\n", t.PermissionsManagePasswordPolicies))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageProfilesPermissionsets: %v\n", t.PermissionsManageProfilesPermissionsets))
	builder.WriteString(fmt.Sprintf("\tPermissionsManagePvtRptsAndDashbds: %v\n", t.PermissionsManagePvtRptsAndDashbds))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageRemoteAccess: %v\n", t.PermissionsManageRemoteAccess))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageReportsInPubFolders: %v\n", t.PermissionsManageReportsInPubFolders))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageRoles: %v\n", t.PermissionsManageRoles))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageSearchPromotionRules: %v\n", t.PermissionsManageSearchPromotionRules))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageSessionPermissionSets: %v\n", t.PermissionsManageSessionPermissionSets))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageSharing: %v\n", t.PermissionsManageSharing))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageSolutions: %v\n", t.PermissionsManageSolutions))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageSurveys: %v\n", t.PermissionsManageSurveys))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageSynonyms: %v\n", t.PermissionsManageSynonyms))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageTemplatedApp: %v\n", t.PermissionsManageTemplatedApp))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageTwoFactor: %v\n", t.PermissionsManageTwoFactor))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageUnlistedGroups: %v\n", t.PermissionsManageUnlistedGroups))
	builder.WriteString(fmt.Sprintf("\tPermissionsManageUsers: %v\n", t.PermissionsManageUsers))
	builder.WriteString(fmt.Sprintf("\tPermissionsMassInlineEdit: %v\n", t.PermissionsMassInlineEdit))
	builder.WriteString(fmt.Sprintf("\tPermissionsMergeTopics: %v\n", t.PermissionsMergeTopics))
	builder.WriteString(fmt.Sprintf("\tPermissionsModerateChatter: %v\n", t.PermissionsModerateChatter))
	builder.WriteString(fmt.Sprintf("\tPermissionsModerateNetworkUsers: %v\n", t.PermissionsModerateNetworkUsers))
	builder.WriteString(fmt.Sprintf("\tPermissionsModifyAllData: %v\n", t.PermissionsModifyAllData))
	builder.WriteString(fmt.Sprintf("\tPermissionsModifyMetadata: %v\n", t.PermissionsModifyMetadata))
	builder.WriteString(fmt.Sprintf("\tPermissionsModifySecureAgents: %v\n", t.PermissionsModifySecureAgents))
	builder.WriteString(fmt.Sprintf("\tPermissionsNewReportBuilder: %v\n", t.PermissionsNewReportBuilder))
	builder.WriteString(fmt.Sprintf("\tPermissionsPackaging2: %v\n", t.PermissionsPackaging2))
	builder.WriteString(fmt.Sprintf("\tPermissionsPasswordNeverExpires: %v\n", t.PermissionsPasswordNeverExpires))
	builder.WriteString(fmt.Sprintf("\tPermissionsPreventClassicExperience: %v\n", t.PermissionsPreventClassicExperience))
	builder.WriteString(fmt.Sprintf("\tPermissionsPublishPackaging: %v\n", t.PermissionsPublishPackaging))
	builder.WriteString(fmt.Sprintf("\tPermissionsRemoveDirectMessageMembers: %v\n", t.PermissionsRemoveDirectMessageMembers))
	builder.WriteString(fmt.Sprintf("\tPermissionsResetPasswords: %v\n", t.PermissionsResetPasswords))
	builder.WriteString(fmt.Sprintf("\tPermissionsRunFlow: %v\n", t.PermissionsRunFlow))
	builder.WriteString(fmt.Sprintf("\tPermissionsRunReports: %v\n", t.PermissionsRunReports))
	builder.WriteString(fmt.Sprintf("\tPermissionsSalesConsole: %v\n", t.PermissionsSalesConsole))
	builder.WriteString(fmt.Sprintf("\tPermissionsScheduleReports: %v\n", t.PermissionsScheduleReports))
	builder.WriteString(fmt.Sprintf("\tPermissionsSelectFilesFromSalesforce: %v\n", t.PermissionsSelectFilesFromSalesforce))
	builder.WriteString(fmt.Sprintf("\tPermissionsSendAnnouncementEmails: %v\n", t.PermissionsSendAnnouncementEmails))
	builder.WriteString(fmt.Sprintf("\tPermissionsSendSitRequests: %v\n", t.PermissionsSendSitRequests))
	builder.WriteString(fmt.Sprintf("\tPermissionsShareInternalArticles: %v\n", t.PermissionsShareInternalArticles))
	builder.WriteString(fmt.Sprintf("\tPermissionsShowCompanyNameAsUserBadge: %v\n", t.PermissionsShowCompanyNameAsUserBadge))
	builder.WriteString(fmt.Sprintf("\tPermissionsSolutionImport: %v\n", t.PermissionsSolutionImport))
	builder.WriteString(fmt.Sprintf("\tPermissionsStdAutomaticActivityCapture: %v\n", t.PermissionsStdAutomaticActivityCapture))
	builder.WriteString(fmt.Sprintf("\tPermissionsSubmitMacrosAllowed: %v\n", t.PermissionsSubmitMacrosAllowed))
	builder.WriteString(fmt.Sprintf("\tPermissionsSubscribeDashboardToOtherUsers: %v\n", t.PermissionsSubscribeDashboardToOtherUsers))
	builder.WriteString(fmt.Sprintf("\tPermissionsSubscribeReportToOtherUsers: %v\n", t.PermissionsSubscribeReportToOtherUsers))
	builder.WriteString(fmt.Sprintf("\tPermissionsSubscribeReportsRunAsUser: %v\n", t.PermissionsSubscribeReportsRunAsUser))
	builder.WriteString(fmt.Sprintf("\tPermissionsSubscribeToLightningDashboards: %v\n", t.PermissionsSubscribeToLightningDashboards))
	builder.WriteString(fmt.Sprintf("\tPermissionsSubscribeToLightningReports: %v\n", t.PermissionsSubscribeToLightningReports))
	builder.WriteString(fmt.Sprintf("\tPermissionsTransferAnyCase: %v\n", t.PermissionsTransferAnyCase))
	builder.WriteString(fmt.Sprintf("\tPermissionsTransferAnyEntity: %v\n", t.PermissionsTransferAnyEntity))
	builder.WriteString(fmt.Sprintf("\tPermissionsTransferAnyLead: %v\n", t.PermissionsTransferAnyLead))
	builder.WriteString(fmt.Sprintf("\tPermissionsTwoFactorApi: %v\n", t.PermissionsTwoFactorApi))
	builder.WriteString(fmt.Sprintf("\tPermissionsUseTeamReassignWizards: %v\n", t.PermissionsUseTeamReassignWizards))
	builder.WriteString(fmt.Sprintf("\tPermissionsUseTemplatedApp: %v\n", t.PermissionsUseTemplatedApp))
	builder.WriteString(fmt.Sprintf("\tPermissionsUseWebLink: %v\n", t.PermissionsUseWebLink))
	builder.WriteString(fmt.Sprintf("\tPermissionsViewAllActivities: %v\n", t.PermissionsViewAllActivities))
	builder.WriteString(fmt.Sprintf("\tPermissionsViewAllData: %v\n", t.PermissionsViewAllData))
	builder.WriteString(fmt.Sprintf("\tPermissionsViewAllUsers: %v\n", t.PermissionsViewAllUsers))
	builder.WriteString(fmt.Sprintf("\tPermissionsViewContent: %v\n", t.PermissionsViewContent))
	builder.WriteString(fmt.Sprintf("\tPermissionsViewDataAssessment: %v\n", t.PermissionsViewDataAssessment))
	builder.WriteString(fmt.Sprintf("\tPermissionsViewDataCategories: %v\n", t.PermissionsViewDataCategories))
	builder.WriteString(fmt.Sprintf("\tPermissionsViewEncryptedData: %v\n", t.PermissionsViewEncryptedData))
	builder.WriteString(fmt.Sprintf("\tPermissionsViewEventLogFiles: %v\n", t.PermissionsViewEventLogFiles))
	builder.WriteString(fmt.Sprintf("\tPermissionsViewHealthCheck: %v\n", t.PermissionsViewHealthCheck))
	builder.WriteString(fmt.Sprintf("\tPermissionsViewHelpLink: %v\n", t.PermissionsViewHelpLink))
	builder.WriteString(fmt.Sprintf("\tPermissionsViewMyTeamsDashboards: %v\n", t.PermissionsViewMyTeamsDashboards))
	builder.WriteString(fmt.Sprintf("\tPermissionsViewOnlyEmbeddedAppUser: %v\n", t.PermissionsViewOnlyEmbeddedAppUser))
	builder.WriteString(fmt.Sprintf("\tPermissionsViewPublicDashboards: %v\n", t.PermissionsViewPublicDashboards))
	builder.WriteString(fmt.Sprintf("\tPermissionsViewPublicReports: %v\n", t.PermissionsViewPublicReports))
	builder.WriteString(fmt.Sprintf("\tPermissionsViewRoles: %v\n", t.PermissionsViewRoles))
	builder.WriteString(fmt.Sprintf("\tPermissionsViewSetup: %v\n", t.PermissionsViewSetup))
	builder.WriteString(fmt.Sprintf("\tPermissionsWaveTabularDownload: %v\n", t.PermissionsWaveTabularDownload))
	builder.WriteString(fmt.Sprintf("\tPermissionsWorkCalibrationUser: %v\n", t.PermissionsWorkCalibrationUser))
	builder.WriteString(fmt.Sprintf("\tPermissionsWorkDotComUserPerm: %v\n", t.PermissionsWorkDotComUserPerm))
	builder.WriteString(fmt.Sprintf("\tProfileId: %v\n", t.ProfileId))
	builder.WriteString(fmt.Sprintf("\tSystemModstamp: %v\n", t.SystemModstamp))

	return builder.String()
}

type PermissionSetQueryResponse struct {
	BaseQuery
	Records []PermissionSet `json:"Records" force:"records"`
}
