// This file was generated for SObject User, API Version v43.0 at 2018-07-30 03:47:25.791676558 -0400 EDT m=+12.134738326

package sobjects

import (
	"fmt"
	"strings"
)

type User struct {
	BaseSObject
	AboutMe                                            string   `force:",omitempty"`
	AccountId                                          string   `force:",omitempty"`
	Address                                            *Address `force:",omitempty"`
	Alias                                              string   `force:",omitempty"`
	BadgeText                                          string   `force:",omitempty"`
	BannerPhotoUrl                                     string   `force:",omitempty"`
	CallCenterId                                       string   `force:",omitempty"`
	City                                               string   `force:",omitempty"`
	CommunityNickname                                  string   `force:",omitempty"`
	CompanyName                                        string   `force:",omitempty"`
	ContactId                                          string   `force:",omitempty"`
	Country                                            string   `force:",omitempty"`
	CreatedById                                        string   `force:",omitempty"`
	CreatedDate                                        string   `force:",omitempty"`
	DefaultGroupNotificationFrequency                  string   `force:",omitempty"`
	DelegatedApproverId                                string   `force:",omitempty"`
	Department                                         string   `force:",omitempty"`
	DigestFrequency                                    string   `force:",omitempty"`
	Division                                           string   `force:",omitempty"`
	Email                                              string   `force:",omitempty"`
	EmailEncodingKey                                   string   `force:",omitempty"`
	EmailPreferencesAutoBcc                            bool     `force:",omitempty"`
	EmailPreferencesAutoBccStayInTouch                 bool     `force:",omitempty"`
	EmailPreferencesStayInTouchReminder                bool     `force:",omitempty"`
	EmployeeNumber                                     string   `force:",omitempty"`
	Extension                                          string   `force:",omitempty"`
	Fax                                                string   `force:",omitempty"`
	FederationIdentifier                               string   `force:",omitempty"`
	FirstName                                          string   `force:",omitempty"`
	ForecastEnabled                                    bool     `force:",omitempty"`
	FullPhotoUrl                                       string   `force:",omitempty"`
	GeocodeAccuracy                                    string   `force:",omitempty"`
	Id                                                 string   `force:",omitempty"`
	IsActive                                           bool     `force:",omitempty"`
	IsExtIndicatorVisible                              bool     `force:",omitempty"`
	IsProfilePhotoActive                               bool     `force:",omitempty"`
	JigsawImportLimitOverride                          int      `force:",omitempty"`
	LanguageLocaleKey                                  string   `force:",omitempty"`
	LastLoginDate                                      string   `force:",omitempty"`
	LastModifiedById                                   string   `force:",omitempty"`
	LastModifiedDate                                   string   `force:",omitempty"`
	LastName                                           string   `force:",omitempty"`
	LastPasswordChangeDate                             string   `force:",omitempty"`
	LastReferencedDate                                 string   `force:",omitempty"`
	LastViewedDate                                     string   `force:",omitempty"`
	Latitude                                           float64  `force:",omitempty"`
	LocaleSidKey                                       string   `force:",omitempty"`
	Longitude                                          float64  `force:",omitempty"`
	ManagerId                                          string   `force:",omitempty"`
	MediumBannerPhotoUrl                               string   `force:",omitempty"`
	MediumPhotoUrl                                     string   `force:",omitempty"`
	MobilePhone                                        string   `force:",omitempty"`
	Name                                               string   `force:",omitempty"`
	OfflinePdaTrialExpirationDate                      string   `force:",omitempty"`
	OfflineTrialExpirationDate                         string   `force:",omitempty"`
	OutOfOfficeMessage                                 string   `force:",omitempty"`
	Phone                                              string   `force:",omitempty"`
	PostalCode                                         string   `force:",omitempty"`
	ProfileId                                          string   `force:",omitempty"`
	ReceivesAdminInfoEmails                            bool     `force:",omitempty"`
	ReceivesInfoEmails                                 bool     `force:",omitempty"`
	SenderEmail                                        string   `force:",omitempty"`
	SenderName                                         string   `force:",omitempty"`
	Signature                                          string   `force:",omitempty"`
	SmallBannerPhotoUrl                                string   `force:",omitempty"`
	SmallPhotoUrl                                      string   `force:",omitempty"`
	State                                              string   `force:",omitempty"`
	StayInTouchNote                                    string   `force:",omitempty"`
	StayInTouchSignature                               string   `force:",omitempty"`
	StayInTouchSubject                                 string   `force:",omitempty"`
	Street                                             string   `force:",omitempty"`
	SystemModstamp                                     string   `force:",omitempty"`
	TimeZoneSidKey                                     string   `force:",omitempty"`
	Title                                              string   `force:",omitempty"`
	UserPermissionsCallCenterAutoLogin                 bool     `force:",omitempty"`
	UserPermissionsInteractionUser                     bool     `force:",omitempty"`
	UserPermissionsJigsawProspectingUser               bool     `force:",omitempty"`
	UserPermissionsKnowledgeUser                       bool     `force:",omitempty"`
	UserPermissionsMarketingUser                       bool     `force:",omitempty"`
	UserPermissionsMobileUser                          bool     `force:",omitempty"`
	UserPermissionsOfflineUser                         bool     `force:",omitempty"`
	UserPermissionsSFContentUser                       bool     `force:",omitempty"`
	UserPermissionsSiteforceContributorUser            bool     `force:",omitempty"`
	UserPermissionsSiteforcePublisherUser              bool     `force:",omitempty"`
	UserPermissionsSupportUser                         bool     `force:",omitempty"`
	UserPermissionsWorkDotComUserFeature               bool     `force:",omitempty"`
	UserPreferencesActivityRemindersPopup              bool     `force:",omitempty"`
	UserPreferencesApexPagesDeveloperMode              bool     `force:",omitempty"`
	UserPreferencesCacheDiagnostics                    bool     `force:",omitempty"`
	UserPreferencesContentEmailAsAndWhen               bool     `force:",omitempty"`
	UserPreferencesContentNoEmail                      bool     `force:",omitempty"`
	UserPreferencesCreateLEXAppsWTShown                bool     `force:",omitempty"`
	UserPreferencesDisCommentAfterLikeEmail            bool     `force:",omitempty"`
	UserPreferencesDisMentionsCommentEmail             bool     `force:",omitempty"`
	UserPreferencesDisProfPostCommentEmail             bool     `force:",omitempty"`
	UserPreferencesDisableAllFeedsEmail                bool     `force:",omitempty"`
	UserPreferencesDisableBookmarkEmail                bool     `force:",omitempty"`
	UserPreferencesDisableChangeCommentEmail           bool     `force:",omitempty"`
	UserPreferencesDisableEndorsementEmail             bool     `force:",omitempty"`
	UserPreferencesDisableFeedbackEmail                bool     `force:",omitempty"`
	UserPreferencesDisableFileShareNotificationsForApi bool     `force:",omitempty"`
	UserPreferencesDisableFollowersEmail               bool     `force:",omitempty"`
	UserPreferencesDisableLaterCommentEmail            bool     `force:",omitempty"`
	UserPreferencesDisableLikeEmail                    bool     `force:",omitempty"`
	UserPreferencesDisableMentionsPostEmail            bool     `force:",omitempty"`
	UserPreferencesDisableMessageEmail                 bool     `force:",omitempty"`
	UserPreferencesDisableProfilePostEmail             bool     `force:",omitempty"`
	UserPreferencesDisableSharePostEmail               bool     `force:",omitempty"`
	UserPreferencesDisableWorkEmail                    bool     `force:",omitempty"`
	UserPreferencesEnableAutoSubForFeeds               bool     `force:",omitempty"`
	UserPreferencesEventRemindersCheckboxDefault       bool     `force:",omitempty"`
	UserPreferencesExcludeMailAppAttachments           bool     `force:",omitempty"`
	UserPreferencesFavoritesShowTopFavorites           bool     `force:",omitempty"`
	UserPreferencesFavoritesWTShown                    bool     `force:",omitempty"`
	UserPreferencesGlobalNavBarWTShown                 bool     `force:",omitempty"`
	UserPreferencesGlobalNavGridMenuWTShown            bool     `force:",omitempty"`
	UserPreferencesHasCelebrationBadge                 bool     `force:",omitempty"`
	UserPreferencesHideBiggerPhotoCallout              bool     `force:",omitempty"`
	UserPreferencesHideCSNDesktopTask                  bool     `force:",omitempty"`
	UserPreferencesHideCSNGetChatterMobileTask         bool     `force:",omitempty"`
	UserPreferencesHideChatterOnboardingSplash         bool     `force:",omitempty"`
	UserPreferencesHideEndUserOnboardingAssistantModal bool     `force:",omitempty"`
	UserPreferencesHideLightningMigrationModal         bool     `force:",omitempty"`
	UserPreferencesHideS1BrowserUI                     bool     `force:",omitempty"`
	UserPreferencesHideSecondChatterOnboardingSplash   bool     `force:",omitempty"`
	UserPreferencesHideSfxWelcomeMat                   bool     `force:",omitempty"`
	UserPreferencesJigsawListUser                      bool     `force:",omitempty"`
	UserPreferencesLightningExperiencePreferred        bool     `force:",omitempty"`
	UserPreferencesPathAssistantCollapsed              bool     `force:",omitempty"`
	UserPreferencesPreviewCustomTheme                  bool     `force:",omitempty"`
	UserPreferencesPreviewLightning                    bool     `force:",omitempty"`
	UserPreferencesRecordHomeReservedWTShown           bool     `force:",omitempty"`
	UserPreferencesRecordHomeSectionCollapseWTShown    bool     `force:",omitempty"`
	UserPreferencesReminderSoundOff                    bool     `force:",omitempty"`
	UserPreferencesShowCityToExternalUsers             bool     `force:",omitempty"`
	UserPreferencesShowCityToGuestUsers                bool     `force:",omitempty"`
	UserPreferencesShowCountryToExternalUsers          bool     `force:",omitempty"`
	UserPreferencesShowCountryToGuestUsers             bool     `force:",omitempty"`
	UserPreferencesShowEmailToExternalUsers            bool     `force:",omitempty"`
	UserPreferencesShowEmailToGuestUsers               bool     `force:",omitempty"`
	UserPreferencesShowFaxToExternalUsers              bool     `force:",omitempty"`
	UserPreferencesShowFaxToGuestUsers                 bool     `force:",omitempty"`
	UserPreferencesShowManagerToExternalUsers          bool     `force:",omitempty"`
	UserPreferencesShowManagerToGuestUsers             bool     `force:",omitempty"`
	UserPreferencesShowMobilePhoneToExternalUsers      bool     `force:",omitempty"`
	UserPreferencesShowMobilePhoneToGuestUsers         bool     `force:",omitempty"`
	UserPreferencesShowPostalCodeToExternalUsers       bool     `force:",omitempty"`
	UserPreferencesShowPostalCodeToGuestUsers          bool     `force:",omitempty"`
	UserPreferencesShowProfilePicToGuestUsers          bool     `force:",omitempty"`
	UserPreferencesShowStateToExternalUsers            bool     `force:",omitempty"`
	UserPreferencesShowStateToGuestUsers               bool     `force:",omitempty"`
	UserPreferencesShowStreetAddressToExternalUsers    bool     `force:",omitempty"`
	UserPreferencesShowStreetAddressToGuestUsers       bool     `force:",omitempty"`
	UserPreferencesShowTitleToExternalUsers            bool     `force:",omitempty"`
	UserPreferencesShowTitleToGuestUsers               bool     `force:",omitempty"`
	UserPreferencesShowWorkPhoneToExternalUsers        bool     `force:",omitempty"`
	UserPreferencesShowWorkPhoneToGuestUsers           bool     `force:",omitempty"`
	UserPreferencesSortFeedByComment                   bool     `force:",omitempty"`
	UserPreferencesSuppressEventSFXReminders           bool     `force:",omitempty"`
	UserPreferencesSuppressTaskSFXReminders            bool     `force:",omitempty"`
	UserPreferencesTaskRemindersCheckboxDefault        bool     `force:",omitempty"`
	UserPreferencesUserDebugModePref                   bool     `force:",omitempty"`
	UserRoleId                                         string   `force:",omitempty"`
	UserType                                           string   `force:",omitempty"`
	Username                                           string   `force:",omitempty"`
}

func (t *User) ApiName() string {
	return "User"
}

func (t *User) String() string {
	builder := strings.Builder{}
	builder.WriteString(fmt.Sprintf("User #%s - %s\n", t.Id, t.Name))
	builder.WriteString(fmt.Sprintf("\tAboutMe: %v\n", t.AboutMe))
	builder.WriteString(fmt.Sprintf("\tAccountId: %v\n", t.AccountId))
	builder.WriteString(fmt.Sprintf("\tAddress: %v\n", t.Address))
	builder.WriteString(fmt.Sprintf("\tAlias: %v\n", t.Alias))
	builder.WriteString(fmt.Sprintf("\tBadgeText: %v\n", t.BadgeText))
	builder.WriteString(fmt.Sprintf("\tBannerPhotoUrl: %v\n", t.BannerPhotoUrl))
	builder.WriteString(fmt.Sprintf("\tCallCenterId: %v\n", t.CallCenterId))
	builder.WriteString(fmt.Sprintf("\tCity: %v\n", t.City))
	builder.WriteString(fmt.Sprintf("\tCommunityNickname: %v\n", t.CommunityNickname))
	builder.WriteString(fmt.Sprintf("\tCompanyName: %v\n", t.CompanyName))
	builder.WriteString(fmt.Sprintf("\tContactId: %v\n", t.ContactId))
	builder.WriteString(fmt.Sprintf("\tCountry: %v\n", t.Country))
	builder.WriteString(fmt.Sprintf("\tCreatedById: %v\n", t.CreatedById))
	builder.WriteString(fmt.Sprintf("\tCreatedDate: %v\n", t.CreatedDate))
	builder.WriteString(fmt.Sprintf("\tDefaultGroupNotificationFrequency: %v\n", t.DefaultGroupNotificationFrequency))
	builder.WriteString(fmt.Sprintf("\tDelegatedApproverId: %v\n", t.DelegatedApproverId))
	builder.WriteString(fmt.Sprintf("\tDepartment: %v\n", t.Department))
	builder.WriteString(fmt.Sprintf("\tDigestFrequency: %v\n", t.DigestFrequency))
	builder.WriteString(fmt.Sprintf("\tDivision: %v\n", t.Division))
	builder.WriteString(fmt.Sprintf("\tEmail: %v\n", t.Email))
	builder.WriteString(fmt.Sprintf("\tEmailEncodingKey: %v\n", t.EmailEncodingKey))
	builder.WriteString(fmt.Sprintf("\tEmailPreferencesAutoBcc: %v\n", t.EmailPreferencesAutoBcc))
	builder.WriteString(fmt.Sprintf("\tEmailPreferencesAutoBccStayInTouch: %v\n", t.EmailPreferencesAutoBccStayInTouch))
	builder.WriteString(fmt.Sprintf("\tEmailPreferencesStayInTouchReminder: %v\n", t.EmailPreferencesStayInTouchReminder))
	builder.WriteString(fmt.Sprintf("\tEmployeeNumber: %v\n", t.EmployeeNumber))
	builder.WriteString(fmt.Sprintf("\tExtension: %v\n", t.Extension))
	builder.WriteString(fmt.Sprintf("\tFax: %v\n", t.Fax))
	builder.WriteString(fmt.Sprintf("\tFederationIdentifier: %v\n", t.FederationIdentifier))
	builder.WriteString(fmt.Sprintf("\tFirstName: %v\n", t.FirstName))
	builder.WriteString(fmt.Sprintf("\tForecastEnabled: %v\n", t.ForecastEnabled))
	builder.WriteString(fmt.Sprintf("\tFullPhotoUrl: %v\n", t.FullPhotoUrl))
	builder.WriteString(fmt.Sprintf("\tGeocodeAccuracy: %v\n", t.GeocodeAccuracy))
	builder.WriteString(fmt.Sprintf("\tId: %v\n", t.Id))
	builder.WriteString(fmt.Sprintf("\tIsActive: %v\n", t.IsActive))
	builder.WriteString(fmt.Sprintf("\tIsExtIndicatorVisible: %v\n", t.IsExtIndicatorVisible))
	builder.WriteString(fmt.Sprintf("\tIsProfilePhotoActive: %v\n", t.IsProfilePhotoActive))
	builder.WriteString(fmt.Sprintf("\tJigsawImportLimitOverride: %v\n", t.JigsawImportLimitOverride))
	builder.WriteString(fmt.Sprintf("\tLanguageLocaleKey: %v\n", t.LanguageLocaleKey))
	builder.WriteString(fmt.Sprintf("\tLastLoginDate: %v\n", t.LastLoginDate))
	builder.WriteString(fmt.Sprintf("\tLastModifiedById: %v\n", t.LastModifiedById))
	builder.WriteString(fmt.Sprintf("\tLastModifiedDate: %v\n", t.LastModifiedDate))
	builder.WriteString(fmt.Sprintf("\tLastName: %v\n", t.LastName))
	builder.WriteString(fmt.Sprintf("\tLastPasswordChangeDate: %v\n", t.LastPasswordChangeDate))
	builder.WriteString(fmt.Sprintf("\tLastReferencedDate: %v\n", t.LastReferencedDate))
	builder.WriteString(fmt.Sprintf("\tLastViewedDate: %v\n", t.LastViewedDate))
	builder.WriteString(fmt.Sprintf("\tLatitude: %v\n", t.Latitude))
	builder.WriteString(fmt.Sprintf("\tLocaleSidKey: %v\n", t.LocaleSidKey))
	builder.WriteString(fmt.Sprintf("\tLongitude: %v\n", t.Longitude))
	builder.WriteString(fmt.Sprintf("\tManagerId: %v\n", t.ManagerId))
	builder.WriteString(fmt.Sprintf("\tMediumBannerPhotoUrl: %v\n", t.MediumBannerPhotoUrl))
	builder.WriteString(fmt.Sprintf("\tMediumPhotoUrl: %v\n", t.MediumPhotoUrl))
	builder.WriteString(fmt.Sprintf("\tMobilePhone: %v\n", t.MobilePhone))
	builder.WriteString(fmt.Sprintf("\tName: %v\n", t.Name))
	builder.WriteString(fmt.Sprintf("\tOfflinePdaTrialExpirationDate: %v\n", t.OfflinePdaTrialExpirationDate))
	builder.WriteString(fmt.Sprintf("\tOfflineTrialExpirationDate: %v\n", t.OfflineTrialExpirationDate))
	builder.WriteString(fmt.Sprintf("\tOutOfOfficeMessage: %v\n", t.OutOfOfficeMessage))
	builder.WriteString(fmt.Sprintf("\tPhone: %v\n", t.Phone))
	builder.WriteString(fmt.Sprintf("\tPostalCode: %v\n", t.PostalCode))
	builder.WriteString(fmt.Sprintf("\tProfileId: %v\n", t.ProfileId))
	builder.WriteString(fmt.Sprintf("\tReceivesAdminInfoEmails: %v\n", t.ReceivesAdminInfoEmails))
	builder.WriteString(fmt.Sprintf("\tReceivesInfoEmails: %v\n", t.ReceivesInfoEmails))
	builder.WriteString(fmt.Sprintf("\tSenderEmail: %v\n", t.SenderEmail))
	builder.WriteString(fmt.Sprintf("\tSenderName: %v\n", t.SenderName))
	builder.WriteString(fmt.Sprintf("\tSignature: %v\n", t.Signature))
	builder.WriteString(fmt.Sprintf("\tSmallBannerPhotoUrl: %v\n", t.SmallBannerPhotoUrl))
	builder.WriteString(fmt.Sprintf("\tSmallPhotoUrl: %v\n", t.SmallPhotoUrl))
	builder.WriteString(fmt.Sprintf("\tState: %v\n", t.State))
	builder.WriteString(fmt.Sprintf("\tStayInTouchNote: %v\n", t.StayInTouchNote))
	builder.WriteString(fmt.Sprintf("\tStayInTouchSignature: %v\n", t.StayInTouchSignature))
	builder.WriteString(fmt.Sprintf("\tStayInTouchSubject: %v\n", t.StayInTouchSubject))
	builder.WriteString(fmt.Sprintf("\tStreet: %v\n", t.Street))
	builder.WriteString(fmt.Sprintf("\tSystemModstamp: %v\n", t.SystemModstamp))
	builder.WriteString(fmt.Sprintf("\tTimeZoneSidKey: %v\n", t.TimeZoneSidKey))
	builder.WriteString(fmt.Sprintf("\tTitle: %v\n", t.Title))
	builder.WriteString(fmt.Sprintf("\tUserPermissionsCallCenterAutoLogin: %v\n", t.UserPermissionsCallCenterAutoLogin))
	builder.WriteString(fmt.Sprintf("\tUserPermissionsInteractionUser: %v\n", t.UserPermissionsInteractionUser))
	builder.WriteString(fmt.Sprintf("\tUserPermissionsJigsawProspectingUser: %v\n", t.UserPermissionsJigsawProspectingUser))
	builder.WriteString(fmt.Sprintf("\tUserPermissionsKnowledgeUser: %v\n", t.UserPermissionsKnowledgeUser))
	builder.WriteString(fmt.Sprintf("\tUserPermissionsMarketingUser: %v\n", t.UserPermissionsMarketingUser))
	builder.WriteString(fmt.Sprintf("\tUserPermissionsMobileUser: %v\n", t.UserPermissionsMobileUser))
	builder.WriteString(fmt.Sprintf("\tUserPermissionsOfflineUser: %v\n", t.UserPermissionsOfflineUser))
	builder.WriteString(fmt.Sprintf("\tUserPermissionsSFContentUser: %v\n", t.UserPermissionsSFContentUser))
	builder.WriteString(fmt.Sprintf("\tUserPermissionsSiteforceContributorUser: %v\n", t.UserPermissionsSiteforceContributorUser))
	builder.WriteString(fmt.Sprintf("\tUserPermissionsSiteforcePublisherUser: %v\n", t.UserPermissionsSiteforcePublisherUser))
	builder.WriteString(fmt.Sprintf("\tUserPermissionsSupportUser: %v\n", t.UserPermissionsSupportUser))
	builder.WriteString(fmt.Sprintf("\tUserPermissionsWorkDotComUserFeature: %v\n", t.UserPermissionsWorkDotComUserFeature))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesActivityRemindersPopup: %v\n", t.UserPreferencesActivityRemindersPopup))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesApexPagesDeveloperMode: %v\n", t.UserPreferencesApexPagesDeveloperMode))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesCacheDiagnostics: %v\n", t.UserPreferencesCacheDiagnostics))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesContentEmailAsAndWhen: %v\n", t.UserPreferencesContentEmailAsAndWhen))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesContentNoEmail: %v\n", t.UserPreferencesContentNoEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesCreateLEXAppsWTShown: %v\n", t.UserPreferencesCreateLEXAppsWTShown))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisCommentAfterLikeEmail: %v\n", t.UserPreferencesDisCommentAfterLikeEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisMentionsCommentEmail: %v\n", t.UserPreferencesDisMentionsCommentEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisProfPostCommentEmail: %v\n", t.UserPreferencesDisProfPostCommentEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisableAllFeedsEmail: %v\n", t.UserPreferencesDisableAllFeedsEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisableBookmarkEmail: %v\n", t.UserPreferencesDisableBookmarkEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisableChangeCommentEmail: %v\n", t.UserPreferencesDisableChangeCommentEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisableEndorsementEmail: %v\n", t.UserPreferencesDisableEndorsementEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisableFeedbackEmail: %v\n", t.UserPreferencesDisableFeedbackEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisableFileShareNotificationsForApi: %v\n", t.UserPreferencesDisableFileShareNotificationsForApi))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisableFollowersEmail: %v\n", t.UserPreferencesDisableFollowersEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisableLaterCommentEmail: %v\n", t.UserPreferencesDisableLaterCommentEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisableLikeEmail: %v\n", t.UserPreferencesDisableLikeEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisableMentionsPostEmail: %v\n", t.UserPreferencesDisableMentionsPostEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisableMessageEmail: %v\n", t.UserPreferencesDisableMessageEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisableProfilePostEmail: %v\n", t.UserPreferencesDisableProfilePostEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisableSharePostEmail: %v\n", t.UserPreferencesDisableSharePostEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesDisableWorkEmail: %v\n", t.UserPreferencesDisableWorkEmail))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesEnableAutoSubForFeeds: %v\n", t.UserPreferencesEnableAutoSubForFeeds))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesEventRemindersCheckboxDefault: %v\n", t.UserPreferencesEventRemindersCheckboxDefault))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesExcludeMailAppAttachments: %v\n", t.UserPreferencesExcludeMailAppAttachments))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesFavoritesShowTopFavorites: %v\n", t.UserPreferencesFavoritesShowTopFavorites))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesFavoritesWTShown: %v\n", t.UserPreferencesFavoritesWTShown))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesGlobalNavBarWTShown: %v\n", t.UserPreferencesGlobalNavBarWTShown))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesGlobalNavGridMenuWTShown: %v\n", t.UserPreferencesGlobalNavGridMenuWTShown))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesHasCelebrationBadge: %v\n", t.UserPreferencesHasCelebrationBadge))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesHideBiggerPhotoCallout: %v\n", t.UserPreferencesHideBiggerPhotoCallout))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesHideCSNDesktopTask: %v\n", t.UserPreferencesHideCSNDesktopTask))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesHideCSNGetChatterMobileTask: %v\n", t.UserPreferencesHideCSNGetChatterMobileTask))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesHideChatterOnboardingSplash: %v\n", t.UserPreferencesHideChatterOnboardingSplash))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesHideEndUserOnboardingAssistantModal: %v\n", t.UserPreferencesHideEndUserOnboardingAssistantModal))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesHideLightningMigrationModal: %v\n", t.UserPreferencesHideLightningMigrationModal))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesHideS1BrowserUI: %v\n", t.UserPreferencesHideS1BrowserUI))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesHideSecondChatterOnboardingSplash: %v\n", t.UserPreferencesHideSecondChatterOnboardingSplash))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesHideSfxWelcomeMat: %v\n", t.UserPreferencesHideSfxWelcomeMat))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesJigsawListUser: %v\n", t.UserPreferencesJigsawListUser))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesLightningExperiencePreferred: %v\n", t.UserPreferencesLightningExperiencePreferred))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesPathAssistantCollapsed: %v\n", t.UserPreferencesPathAssistantCollapsed))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesPreviewCustomTheme: %v\n", t.UserPreferencesPreviewCustomTheme))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesPreviewLightning: %v\n", t.UserPreferencesPreviewLightning))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesRecordHomeReservedWTShown: %v\n", t.UserPreferencesRecordHomeReservedWTShown))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesRecordHomeSectionCollapseWTShown: %v\n", t.UserPreferencesRecordHomeSectionCollapseWTShown))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesReminderSoundOff: %v\n", t.UserPreferencesReminderSoundOff))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowCityToExternalUsers: %v\n", t.UserPreferencesShowCityToExternalUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowCityToGuestUsers: %v\n", t.UserPreferencesShowCityToGuestUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowCountryToExternalUsers: %v\n", t.UserPreferencesShowCountryToExternalUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowCountryToGuestUsers: %v\n", t.UserPreferencesShowCountryToGuestUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowEmailToExternalUsers: %v\n", t.UserPreferencesShowEmailToExternalUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowEmailToGuestUsers: %v\n", t.UserPreferencesShowEmailToGuestUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowFaxToExternalUsers: %v\n", t.UserPreferencesShowFaxToExternalUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowFaxToGuestUsers: %v\n", t.UserPreferencesShowFaxToGuestUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowManagerToExternalUsers: %v\n", t.UserPreferencesShowManagerToExternalUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowManagerToGuestUsers: %v\n", t.UserPreferencesShowManagerToGuestUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowMobilePhoneToExternalUsers: %v\n", t.UserPreferencesShowMobilePhoneToExternalUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowMobilePhoneToGuestUsers: %v\n", t.UserPreferencesShowMobilePhoneToGuestUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowPostalCodeToExternalUsers: %v\n", t.UserPreferencesShowPostalCodeToExternalUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowPostalCodeToGuestUsers: %v\n", t.UserPreferencesShowPostalCodeToGuestUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowProfilePicToGuestUsers: %v\n", t.UserPreferencesShowProfilePicToGuestUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowStateToExternalUsers: %v\n", t.UserPreferencesShowStateToExternalUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowStateToGuestUsers: %v\n", t.UserPreferencesShowStateToGuestUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowStreetAddressToExternalUsers: %v\n", t.UserPreferencesShowStreetAddressToExternalUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowStreetAddressToGuestUsers: %v\n", t.UserPreferencesShowStreetAddressToGuestUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowTitleToExternalUsers: %v\n", t.UserPreferencesShowTitleToExternalUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowTitleToGuestUsers: %v\n", t.UserPreferencesShowTitleToGuestUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowWorkPhoneToExternalUsers: %v\n", t.UserPreferencesShowWorkPhoneToExternalUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesShowWorkPhoneToGuestUsers: %v\n", t.UserPreferencesShowWorkPhoneToGuestUsers))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesSortFeedByComment: %v\n", t.UserPreferencesSortFeedByComment))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesSuppressEventSFXReminders: %v\n", t.UserPreferencesSuppressEventSFXReminders))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesSuppressTaskSFXReminders: %v\n", t.UserPreferencesSuppressTaskSFXReminders))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesTaskRemindersCheckboxDefault: %v\n", t.UserPreferencesTaskRemindersCheckboxDefault))
	builder.WriteString(fmt.Sprintf("\tUserPreferencesUserDebugModePref: %v\n", t.UserPreferencesUserDebugModePref))
	builder.WriteString(fmt.Sprintf("\tUserRoleId: %v\n", t.UserRoleId))
	builder.WriteString(fmt.Sprintf("\tUserType: %v\n", t.UserType))
	builder.WriteString(fmt.Sprintf("\tUsername: %v\n", t.Username))

	return builder.String()
}

type UserQueryResponse struct {
	BaseQuery
	Records []User `json:"Records" force:"records"`
}
